#!/usr/bin/env python3
"""Write `src/satellite_help/help.def` -- the entries, as data the interpreter
compiles in.

ONE SOURCE, TWO ARTIFACTS. `HELP.md` is for a person reading the repository and
`help.def` is for `satellite.help` answering inside a program, and they are
generated side by side from `entries_*.json` in one run of gen.py so that
neither can say something the other does not. A second document is the drift
DESIGN §4.6 exists to remove, and a hand-maintained C++ copy of 264 entries
would be exactly that with a compiler in front of it.

WHY THE HEAD IS A NODE AND NOT THE QUERY STRING. Each entry carries the `>`
line it is brought up by -- `satellite.help(satellite.console.input)` for all
three shapes of `input` -- and that line is the GROUP: asking about a path must
answer for the node and the shapes written beside it at once. Stored as text the
interpreter would have to walk it back to a node on every ask; stored as the
node it walks to, the grouping is an integer compare and the walk happened here.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "src", "satellite_help", "help.def")

HEADER = '''// Every node's help, as data. GENERATED by help_lines/defgen.py -- edit
// help_lines/entries_*.json and run `python3 help_lines/gen.py`.
//
// THE SAME X-MACRO SHAPE AS words.def AND errors.def, and for the third time
// the same reason: a consumer defines SAT_HELP, includes this file, and undefines
// it again, so the table, the walk and the invariants all come from one list and
// cannot drift apart.
//
//     SAT_HELP(ident, head, prose, example)
//
// `ident` is the node's `words::NodeId`, and there is EXACTLY ONE ROW PER NODE
// IN words.def ORDER -- satellite_help/help_text.hpp asserts both at compile
// time, so a word appended to the registry with no entry here is a build error
// naming the node rather than a silence a person has to notice.
//
// `head` is the node this entry is asked about UNDER, which is what makes
// `satellite.help(satellite.console.input)` answer for `input()`, `input(prompt)`
// and `input(prompt, target)` together: all three carry head CONSOLE_INPUT_0.
// A node that heads its own group carries itself, and help_text.hpp asserts that
// a head is always its own head -- so the groups partition the registry and no
// entry can be unreachable.
//
// `prose` is what the entry says, `\\n` for a line break and `\\n\\n` between
// paragraphs. `example` is the worked line, or "" where writing one would be
// inventing the language -- which is what an unbuilt path gets, and is the whole
// of DESIGN §1.1 applied to a help text.
//
// EVERY NON-EMPTY EXAMPLE IN HERE HAS BEEN RUN. help_lines/verify.py wraps each
// one into a program and executes it against the interpreter in this tree; the
// five statements that were confidently written and false are listed in
// help_lines/README.md, and they are why the script exists rather than why it is
// tidy.

#ifndef SAT_HELP
#define SAT_HELP(ident, head, prose, example)
#endif

'''


def literal(text):
    """A C string literal, one source line per line of prose."""
    if not text:
        return '""'
    lines = text.split("\n")
    out = []
    for i, line in enumerate(lines):
        body = line.replace("\\", "\\\\").replace('"', '\\"')
        if i != len(lines) - 1:
            body += "\\n"
        out.append('"%s"' % body)
    return out


def write(nodes, entries, bypath):
    rows = sorted(nodes.values(), key=lambda n: n.order)
    out = [HEADER]
    for n in rows:
        e = entries[n.number]
        inner = e["query"][len("satellite.help("):-1]
        head = bypath[inner]
        out.append("// %s  %s" % (n.number, n.path))
        out.append("SAT_HELP(%s, %s," % (n.ident, head.ident))
        for piece in _indent(literal(e["prose"].strip("\n"))):
            out.append(piece)
        out.append("         ,")
        for piece in _indent(literal(e.get("example", "").strip("\n"))):
            out.append(piece)
        out.append("         )")
        out.append("")
    out.append("#undef SAT_HELP")
    text = "\n".join(out) + "\n"

    # AN UNCHANGED FILE IS NOT REWRITTEN, and that is not tidiness. help.def is
    # a prerequisite of every object in the build and topics.py refuses to ask a
    # `satl` older than it -- so a generator that stamped a new mtime on
    # identical bytes would rebuild the whole tree on every run of gen.py and
    # then declare the binary stale anyway. Writing only on a real change is
    # what makes both of those checks mean something.
    try:
        if open(OUT).read() == text:
            return len(rows)
    except OSError:
        pass
    with open(OUT, "w") as f:
        f.write(text)
    return len(rows)


def _indent(lit):
    if isinstance(lit, str):
        return ["         " + lit]
    return ["         " + line for line in lit]
