#!/usr/bin/env python3
# satellite/bytecode/make_word_codes.py -- reads words/words.tsv and writes
# word_codes.hpp. Run it after regenerating the word table; never edit the header.
#
# THERE IS NO SECOND SET OF NUMBERS TO MAINTAIN, which is the point of doing it
# this way. A word's 16-bit code is 4097 plus its ROW in words/words.tsv, so the
# word table stays the one authority (DESIGN §3.2) and the code is a projection
# of it. Nothing here is hand-assigned, so the two cannot disagree.
#
# WHAT THIS BUYS: a .sat file stores a word as its path numbers -- 1 5 1 -- and
# the interpreter wants one 16-bit code. code_of(1, 5, 1) is that conversion, and
# numbers_of(code) is the way back for whatever writes a .sat file out again.
#
# SORTED KEYS, BINARY SEARCH. A linear scan over 364 rows would be ~109 million
# comparisons on a 100,000-line program; nine steps is not.

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
WORDS = os.path.join(HERE, "..", "..", "words", "words.tsv")
# Second spellings of a word (words/aliases.tsv says why they have no row).
ALIASES = os.path.join(HERE, "..", "..", "words", "aliases.tsv")
HEADER = os.path.join(HERE, "word_codes.hpp")

WORD_BASE = 4096         # reserved: no word has this code (the author, 2026-09-16)
FIRST_WORD = 4097
LAST_WORD = 8191         # 4096 + 4096 - 1
MAX_DEPTH = 7            # numbers a packed key holds
MAX_NUMBER = 255         # the largest a packed number may be


def packed(numbers):
    """The 64-bit key: depth in the top byte, then a byte a number.

    None when the word cannot be packed -- deeper than MAX_DEPTH or a number
    past MAX_NUMBER. Such a word simply has no 16-bit code, and travels as
    word_number_token and its numbers instead, which has no ceiling at all.
    """
    if len(numbers) > MAX_DEPTH or any(n > MAX_NUMBER or n < 0 for n in numbers):
        return None
    key = len(numbers) << 56
    for i, n in enumerate(numbers):
        key |= n << (48 - i * 8)
    return key


def main():
    rows = []
    with open(WORDS, encoding="utf-8") as handle:
        for line in handle:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 2 or not parts[0].strip():
                continue
            rows.append(([int(n) for n in parts[0].split()], parts[1]))

    if not rows:
        sys.exit("make_word_codes.py: words.tsv held no rows")
    if FIRST_WORD + len(rows) - 1 > LAST_WORD:
        sys.exit("make_word_codes.py: %d words do not fit in %d..%d"
                 % (len(rows), FIRST_WORD, LAST_WORD))

    keyed, unpackable = [], []
    for index, (numbers, path) in enumerate(rows):
        key = packed(numbers)
        (keyed if key is not None else unpackable).append((key, FIRST_WORD + index, path, numbers))
    keyed.sort(key=lambda row: row[0])

    seen = {}
    for key, code, path, _ in keyed:
        if key in seen:
            sys.exit("make_word_codes.py: %s and %s pack to the same key" % (seen[key], path))
        seen[key] = path

    # THE SECOND SPELLINGS, each spelled to its word's code. The file is typed by
    # hand, so a row that could not mean what it says stops the script: a spelling
    # that is already a word would give that word a second code's worth of doubt,
    # and a word that is not one would lex as nothing.
    spelled = [(path, FIRST_WORD + i) for i, (_, path) in enumerate(rows)]
    code_of = dict(spelled)
    words = set(code_of)                  # the real words: an alias of an alias is refused
    for number, line in enumerate(open(ALIASES, encoding="utf-8") if os.path.exists(ALIASES) else [], 1):
        if not line.strip() or line.startswith("#"):
            continue
        fields = line.rstrip("\n").split("\t")
        if len(fields) != 2 or not all(field and field == field.strip() for field in fields):
            sys.exit("make_word_codes.py: aliases.tsv line %d: write the spelling, a tab, then the word" % number)
        alias, word = fields
        if alias in code_of:
            sys.exit("make_word_codes.py: aliases.tsv line %d: %s is already a word" % (number, alias))
        if word not in words:
            sys.exit("make_word_codes.py: aliases.tsv line %d: %s is not a word" % (number, word))
        code_of[alias] = code_of[word]
        spelled.append((alias, code_of[word]))

    out = ['#pragma once',
           '// satellite/bytecode/word_codes.hpp -- GENERATED by make_word_codes.py',
           '// from words/words.tsv. Do not edit: edit the word table and run the script.',
           '//',
           '// EVERY satellite.something.something HAS A 16-BIT CODE, %d..%d' % (WORD_BASE, LAST_WORD),
           '// (the author, 2026-09-16). %d is reserved and no word has it; the words' % WORD_BASE,
           '// start at %d and a word\'s code is %d plus its ROW in words.tsv.' % (FIRST_WORD, FIRST_WORD),
           '//',
           '// TWO NUMBERS, ONE TABLE. A .sat file stores a word as its path numbers',
           '// (1 5 1); the interpreter holds one 16-bit code (%d). They are not the same' % (FIRST_WORD + 66),
           '// number and cannot be -- a path is a tree of any depth, a code is flat and',
           '// fixed width -- but only the path numbers are maintained. The code is a',
           '// projection of the row, so there is no second set to keep in step.',
           '//',
           '// A CODE IS A FAST PATH AND NEVER A CEILING. code_of() answers 0 -- the',
           '// registry\'s own "nothing" -- for a word with no code, and the caller then',
           '// writes word_number_token and the numbers, which has no limit.',
           '//',
           '// Generated, so it is exempt from the 300-line rule, like words.def was.',
           '',
           '#include "token_codes.hpp"',
           '',
           '#include <cstddef>',
           '#include <cstdint>',
           '#include <string_view>',
           '#include <type_traits>',
           '',
           'namespace satellite004 {',
           'namespace word {',
           '',
           'inline constexpr token::Code kBase = %d;       // reserved: no word has it' % WORD_BASE,
           'inline constexpr token::Code kFirst = %d;      // satellite' % FIRST_WORD,
           'inline constexpr token::Code kLast = %d;       // the end of the range' % LAST_WORD,
           'inline constexpr unsigned int kWordsInTable = %d;' % len(rows),
           'inline constexpr unsigned int kMaxDepth = %d;' % MAX_DEPTH,
           '',
           'inline constexpr bool is_word_code(token::Code code) { return code >= kBase && code <= kLast; }',
           '',
           '// depth in the top byte, then a byte a number. 0 when it will not pack.',
           'inline constexpr std::uint64_t key_of(const int *numbers, std::size_t depth)',
           '{',
           '    if (depth == 0 || depth > kMaxDepth) return 0;',
           '    std::uint64_t key = static_cast<std::uint64_t>(depth) << 56;',
           '    for (std::size_t i = 0; i < depth; ++i) {',
           '        if (numbers[i] < 0 || numbers[i] > 255) return 0;',
           '        key |= static_cast<std::uint64_t>(numbers[i]) << (48 - i * 8);',
           '    }',
           '    return key;',
           '}',
           '',
           'struct KeyedWord { std::uint64_t key; token::Code code; };',
           '',
           '// Sorted by key, so code_of() is a binary search and not 364 compares.',
           'inline constexpr KeyedWord kKeyedWords[] = {']
    for key, code, path, numbers in keyed:
        out.append('    {0x%016XULL, %d},  // %s -- %s' % (key, code, " ".join(str(n) for n in numbers), path))
    out += ['};',
            '',
            'inline constexpr std::size_t kKeyedWordCount = sizeof kKeyedWords / sizeof kKeyedWords[0];',
            '',
            '// The numbers and the spelling behind each code, indexed by code - kFirst.',
            'struct WordFacts { const char *path; int numbers[kMaxDepth]; unsigned int depth; };',
            '',
            'inline constexpr WordFacts kWordFacts[] = {']
    for numbers, path in rows:
        filled = list(numbers) + [0] * (MAX_DEPTH - len(numbers))
        out.append('    {"%s", {%s}, %d},' % (path, ", ".join(str(n) for n in filled[:MAX_DEPTH]), len(numbers)))
    out += ['};',
            '',
            'inline constexpr std::size_t kWordFactsCount = sizeof kWordFacts / sizeof kWordFacts[0];',
            '',
            '// The same words sorted by SPELLING, so the lexer can turn the text',
            '// satellite.console.display into one code without walking 364 rows --',
            '// and words/aliases.tsv\'s second spellings among them, each with its',
            '// word\'s code, so satellite.space lexes as satellite.namespace.',
            'struct SpelledWord { const char *path; token::Code code; };',
            '',
            'inline constexpr SpelledWord kSpelledWords[] = {']
    for path, code in sorted(spelled):
        out.append('    {"%s", %d},' % (path, code))
    out += ['};',
            '',
            'inline constexpr std::size_t kSpelledWordCount = sizeof kSpelledWords / sizeof kSpelledWords[0];',
            '',
            '// THE CONVERSION. A .sat file stores a word as int int int int; this is how',
            '// that becomes the one 16-bit code the interpreter holds.',
            '//',
            '//     code_of(1, 5, 1)  ->  %d   satellite.console.display' % (FIRST_WORD + 66),
            '//     code_of(1)        ->  %d   satellite' % FIRST_WORD,
            '//',
            '// ANSWERS 0 -- the registry\'s "nothing" -- when the word has no code: not in',
            '// the table, deeper than kMaxDepth, or a number past 255. The caller then',
            '// writes word_number_token and the numbers, which has no ceiling, so a',
            '// language with no limits keeps none here either.',
            'inline token::Code code_of(const int *numbers, std::size_t depth)',
            '{',
            '    const std::uint64_t key = key_of(numbers, depth);',
            '    if (key == 0) return 0;',
            '    std::size_t low = 0, high = kKeyedWordCount;',
            '    while (low < high) {',
            '        const std::size_t middle = low + (high - low) / 2;',
            '        if (kKeyedWords[middle].key < key) low = middle + 1;',
            '        else high = middle;',
            '    }',
            '    if (low < kKeyedWordCount && kKeyedWords[low].key == key) return kKeyedWords[low].code;',
            '    return 0;',
            '}',
            '',
            '// code_of(1, 5, 1) -- the spelling a .sat file\'s int int int int reads as.',
            '//',
            '// CONSTRAINED TO INTEGERS on purpose: unconstrained, this swallowed',
            '// code_of(pointer, depth) too and tried to cast the pointer to an int.',
            'template <class... Numbers>',
            '    requires (sizeof...(Numbers) > 0 && (... && std::is_integral_v<Numbers>))',
            'inline token::Code code_of(Numbers... numbers)',
            '{',
            '    const int written[] = {static_cast<int>(numbers)...};',
            '    return code_of(written, sizeof...(Numbers));',
            '}',
            '',
            '// The way back, for whatever writes a .sat file out again. Answers nullptr',
            '// and leaves `depth` at 0 when `code` is not a word this table holds.',
            'inline const int *numbers_of(token::Code code, unsigned int &depth)',
            '{',
            '    depth = 0;',
            '    if (code < kFirst || code >= kFirst + kWordFactsCount) return nullptr;',
            '    const WordFacts &facts = kWordFacts[code - kFirst];',
            '    depth = facts.depth;',
            '    return facts.numbers;',
            '}',
            '',
            '// The code for a spelling, or 0. The lexer\'s way in: it has the TEXT',
            '// satellite.console.display and wants 4163, without ever building numbers.',
            'inline token::Code code_of_spelling(std::string_view path)',
            '{',
            '    std::size_t low = 0, high = kSpelledWordCount;',
            '    while (low < high) {',
            '        const std::size_t middle = low + (high - low) / 2;',
            '        if (std::string_view(kSpelledWords[middle].path) < path) low = middle + 1;',
            '        else high = middle;',
            '    }',
            '    if (low < kSpelledWordCount && std::string_view(kSpelledWords[low].path) == path)',
            '        return kSpelledWords[low].code;',
            '    return 0;',
            '}',
            '',
            '// "satellite.console.display", or nullptr. What the converters print.',
            'inline const char *spelling_of(token::Code code)',
            '{',
            '    if (code < kFirst || code >= kFirst + kWordFactsCount) return nullptr;',
            '    return kWordFacts[code - kFirst].path;',
            '}',
            '',
            '} // namespace word',
            '} // namespace satellite004',
            '']

    with open(HEADER, "w", encoding="utf-8") as handle:
        handle.write("\n".join(out))
    print("word_codes.hpp: %d words, codes %d..%d, %d unpackable"
          % (len(rows), FIRST_WORD, FIRST_WORD + len(rows) - 1, len(unpackable)))


if __name__ == "__main__":
    main()
