#!/usr/bin/env python3
# satellite/bytecode/make_token_codes.py -- reads REGISTRY.satellite and writes
# token_codes.hpp. Run it after editing the registry; never edit the header.
#
# ONE FILE, ONE ANSWER (REGISTRY.satellite's own rule). The lexer must not carry
# a second copy of what a code means, so the only copy a C++ file sees is
# generated from the registry's own rows and carries the registry's own words.

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REGISTRY = os.path.join(HERE, "..", "..", "REGISTRY.satellite")
HEADER = os.path.join(HERE, "token_codes.hpp")


def rows(text):
    """Every (code, name, what) the registry defines, characters and tokens.

    Rows start after the dashed rule, so the header's prose -- which quotes
    codes like 0000100100000000 in the middle of a sentence -- is never read as
    one. A row is sixteen 0/1, exactly two spaces, then the name.
    """
    started = False
    for line in text.splitlines():
        if not started:
            started = line.startswith("-----")
            continue
        if len(line) < 18 or line[:16].strip("01") or line[16:18] != "  ":
            continue
        bits, rest = line[:16], line[18:].strip()
        if not rest:
            continue
        name, _, what = rest.partition("  ")
        yield int(bits, 2), name.strip(), what.strip()


def main():
    with open(REGISTRY, encoding="utf-8") as handle:
        text = handle.read()

    # 4096..8191 is the WORD range, and word_codes.hpp owns it. Its rows are
    # prose ("the first word"), not identifiers, so they would not compile here
    # even if they belonged -- which they do not: a word's code comes from
    # words.tsv, never from this file.
    tokens = [(code, name, what) for code, name, what in rows(text)
              if code >= 256 and name != "free" and not (4096 <= code <= 8191)]
    if not tokens:
        sys.exit("make_token_codes.py: REGISTRY.satellite defined no tokens")

    first = min(code for code, _, _ in tokens)
    if first != 256:
        sys.exit("make_token_codes.py: the first token is %d, not 256" % first)

    seen = {}
    for code, name, _ in tokens:
        if code in seen:
            sys.exit("make_token_codes.py: %d is both %s and %s" % (code, seen[code], name))
        seen[code] = name

    out = ['#pragma once',
           '// satellite/bytecode/token_codes.hpp -- GENERATED by make_token_codes.py',
           '// from REGISTRY.satellite. Do not edit: edit the registry and run the script.',
           '//',
           '// A code below 256 is a character; 256 and up is a token (the author,',
           '// 2026-09-16). is_token() is the one test, and it is the high byte.',
           '',
           '#include <cstdint>',
           '',
           'namespace satellite004 {',
           'namespace token {',
           '',
           'using Code = std::uint16_t;',
           '',
           'inline constexpr bool is_token(Code code) { return (code >> 8) != 0; }',
           'inline constexpr bool is_character(Code code) { return (code >> 8) == 0; }',
           'inline constexpr Code family_of(Code code) { return static_cast<Code>(code >> 8); }',
           '',
           '// A COUNTED token is followed by a count and then that many codes, which',
           '// are SKIPPED and never classified. The count continues into the next code',
           '// when that code is long_count_token, so no literal has a ceiling.',
           '//',
           '// THIS IS NOT A FAMILY TEST, and it used to be, which was a defect. A family',
           '// says what a token MEANS; carrying a count is what it does STRUCTURALLY,',
           '// and the two do not line up -- error_token is in the stream family and IS',
           '// counted, comment_token is in the text family and is a marker only. Testing',
           '// the family let a reader walk into a payload\'s length as though it were a',
           '// token (found by the checks, 2026-09-16). The rows marked [COUNTED] in',
           '// REGISTRY.satellite are the list, and this switch is generated from them.',
           'inline constexpr bool carries_a_count(Code code)',
           '{',
           '    switch (code) {']
    by_name = {name: code for code, name, _ in tokens}
    counted = [name for _, name, what in tokens if what.startswith("[COUNTED]")]
    if not counted:
        sys.exit("make_token_codes.py: REGISTRY.satellite marked no rows [COUNTED]")
    for name in counted:
        out.append('    case 0x%04X:  // %s' % (by_name[name], name))
    out += ['        return true;',
            '    default:',
            '        return false;',
            '    }',
            '}',
            '']
    for code, name, what in tokens:
        out.append('inline constexpr Code %s = 0x%04X;  // %s' % (name, code, what[:88]))
    out += ['',
            'inline constexpr int kTokenCount = %d;' % len(tokens),
            '',
            '} // namespace token',
            '} // namespace satellite004',
            '']

    with open(HEADER, "w", encoding="utf-8") as handle:
        handle.write("\n".join(out))
    print("token_codes.hpp: %d tokens, %d..%d" % (len(tokens), first, max(seen)))


if __name__ == "__main__":
    main()
