#!/usr/bin/env python3
# satellite/bytecode/make_token_codes.py -- reads REGISTRY.satellite and writes
# token_codes.hpp. Run it after editing the registry; never edit the header.
#
# ONE FILE, ONE ANSWER (REGISTRY.satellite's own rule). The lexer must not carry
# a second copy of what a code means, so the only copy a C++ file sees is
# generated from the registry's own rows and carries the registry's own words.

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REGISTRY = os.path.join(HERE, "..", "..", "REGISTRY.satellite")
HEADER = os.path.join(HERE, "token_codes.hpp")


def rows(text):
    """Every (code, name, what) the registry defines, characters and tokens.

    Rows start after the dashed rule, so the header's prose -- which quotes
    codes like 0000100100000000 in the middle of a sentence -- is never read as
    one. A row is sixteen 0/1, exactly two spaces, then the name.
    """
    started = False
    for line in text.splitlines():
        if not started:
            started = line.startswith("-----")
            continue
        if len(line) < 18 or line[:16].strip("01") or line[16:18] != "  ":
            continue
        bits, rest = line[:16], line[18:].strip()
        if not rest:
            continue
        name, _, what = rest.partition("  ")
        yield int(bits, 2), name.strip(), what.strip()


def main():
    with open(REGISTRY, encoding="utf-8") as handle:
        text = handle.read()

    # 4096..8191 is the WORD range, and word_codes.hpp owns it. Its rows are
    # prose ("the first word"), not identifiers, so they would not compile here
    # even if they belonged -- which they do not: a word's code comes from
    # words.tsv, never from this file.
    tokens = [(code, name, what) for code, name, what in rows(text)
              if code >= 256 and name != "free" and not (4096 <= code <= 8191)]
    if not tokens:
        sys.exit("make_token_codes.py: REGISTRY.satellite defined no tokens")

    first = min(code for code, _, _ in tokens)
    if first != 256:
        sys.exit("make_token_codes.py: the first token is %d, not 256" % first)

    seen = {}
    for code, name, _ in tokens:
        if code in seen:
            sys.exit("make_token_codes.py: %d is both %s and %s" % (code, seen[code], name))
        seen[code] = name

    # A FAMILY'S `free` ROW STARTS ABOVE EVERY CODE THE FAMILY USES. The check
    # above never saw this: it skips `free` rows, so the method family's free row
    # sat on sort_token's own code (0000101100011110) through six new methods,
    # and the next person to take "the first free code" would have taken sort's
    # (found by the SATELLITE_INFINITY.md design panel, 2026-09-18).
    # AND A FREE RANGE HOLDS NO USED CODE: its `to` end is read too, so a range that
    # runs over a code already given out is refused, not just one that starts on it.
    for code, name, what in rows(text):
        if name != "free" or code < 256 or 4096 <= code <= 8191:
            continue
        used = [taken for taken in seen if taken >> 8 == code >> 8]
        if used and code <= max(used):
            sys.exit("make_token_codes.py: the free row %s says %d is free, but %s is %d; free starts at %d"
                     % (format(code, "016b"), code, seen[max(used)], max(used), max(used) + 1))
        end = what.split()[1] if what.startswith("to ") else None
        if end is None or end.rstrip(",").strip("01") or len(end.rstrip(",")) != 16:
            sys.exit("make_token_codes.py: the free row %s does not say `to <16 bits>`" % format(code, "016b"))
        inside = [taken for taken in seen if code <= taken <= int(end.rstrip(","), 2)]
        if inside:
            sys.exit("make_token_codes.py: the free row %s runs to %s, over %s (%d)"
                     % (format(code, "016b"), end.rstrip(","), seen[min(inside)], min(inside)))

    out = ['#pragma once',
           '// satellite/bytecode/token_codes.hpp -- GENERATED by make_token_codes.py',
           '// from REGISTRY.satellite. Do not edit: edit the registry and run the script.',
           '//',
           '// A code below 256 is a character; 256 and up is a token (the author,',
           '// 2026-09-16). is_token() is the one test, and it is the high byte.',
           '',
           '#include <cstdint>',
           '#include <string_view>',
           '',
           'namespace satellite004 {',
           'namespace token {',
           '',
           'using Code = std::uint16_t;',
           '',
           'inline constexpr bool is_token(Code code) { return (code >> 8) != 0; }',
           'inline constexpr bool is_character(Code code) { return (code >> 8) == 0; }',
           'inline constexpr Code family_of(Code code) { return static_cast<Code>(code >> 8); }',
           '',
           '// A COUNTED token is followed by a count and then that many codes, which',
           '// are SKIPPED and never classified. The count continues into the next code',
           '// when that code is long_count_token, so no literal has a ceiling.',
           '//',
           '// THIS IS NOT A FAMILY TEST, and it used to be, which was a defect. A family',
           '// says what a token MEANS; carrying a count is what it does STRUCTURALLY,',
           '// and the two do not line up -- error_token is in the stream family and IS',
           '// counted, comment_token is in the text family and is a marker only. Testing',
           '// the family let a reader walk into a payload\'s length as though it were a',
           '// token (found by the checks, 2026-09-16). The rows marked [COUNTED] in',
           '// REGISTRY.satellite are the list, and this switch is generated from them.',
           'inline constexpr bool carries_a_count(Code code)',
           '{',
           '    switch (code) {']
    by_name = {name: code for code, name, _ in tokens}
    counted = [name for _, name, what in tokens if what.startswith("[COUNTED]")]
    if not counted:
        sys.exit("make_token_codes.py: REGISTRY.satellite marked no rows [COUNTED]")
    for name in counted:
        out.append('    case 0x%04X:  // %s' % (by_name[name], name))
    out += ['        return true;',
            '    default:',
            '        return false;',
            '    }',
            '}',
            '']
    for code, name, what in tokens:
        out.append('inline constexpr Code %s = 0x%04X;  // %s' % (name, code, what[:88]))

    # THE METHOD NAMES -- the author, 2026-09-16: "we make find_token, so when we
    # have period token and find_token together with parentheses token, with all
    # of those tokens it triggers a detailed code". A method's NAME gets its own
    # 16-bit code, so recognising `.find(` is two integer compares and not a
    # string compare. The rows marked [METHOD] are the list; the word before the
    # mark is the spelling the lexer matches, and it is matched ONLY straight
    # after a method_token, so a variable may still be named `find`.
    # ALIASES ARE A LEXER TABLE, NOT A DISPATCH CONCERN (the author, 2026-09-16:
    # "these are just one command and aliases by the way"). A [METHOD] row's
    # spelling field may hold several spellings separated by `/`, and EVERY ONE
    # OF THEM LEXES TO THE SAME CODE -- so `n.to_string()`, `n.str()` and
    # `n.string()` are one token before anything downstream sees them, and
    # nothing after the lexer ever learns there were three spellings. That is
    # 003's own rule for `satellite.class` aliasing `satellite.spacesuit`:
    # "the parser never learns there were two spellings".
    methods = []
    for _, name, what in tokens:
        if "[METHOD]" not in what:
            continue
        for spelling in what.split()[0].split("/"):
            methods.append((name, spelling))
    out += ['',
            '// GENERATED from the [METHOD] rows: a method\'s FIRST spelling, "" for a code',
            '// that is not a method. The hand-written name functions fall back to this, so',
            '// a method added to the registry is never named "that method" in a refusal',
            '// (SATELLITE_INFINITY.md, INF-1, found when power_of was).',
            'inline constexpr const char *method_name_of(Code code)',
            '{']
    for name in dict.fromkeys(n for n, _ in methods):
        out.append('    if (code == %s) return "%s";' % (name, next(s for n, s in methods if n == name)))
    out += ['    return "";',
            '}',
            '',
            '// GENERATED from the [METHOD] rows. Answers 0 for a name that is not a',
            '// method of the language -- a user\'s own method keeps name_token.',
            'inline constexpr Code method_code_of(std::string_view spelling)',
            '{']
    for name, spelling in methods:
        out.append('    if (spelling == "%s") return %s;' % (spelling, name))
    out += ['    return 0;',
            '}',
            '',
            '// True for a code that names a method. One compare, because the family is',
            '// its own: every method name shares the high byte.',
            'inline constexpr bool is_method_code(Code code)',
            '{',
            '    return %s;' % (' || '.join('code == %s' % n for n in dict.fromkeys(n for n, _ in methods)) if methods else 'false'),
            '}',
            '']
    out += ['',
            'inline constexpr int kTokenCount = %d;' % len(tokens),
            '',
            '} // namespace token',
            '} // namespace satellite004',
            '']

    with open(HEADER, "w", encoding="utf-8") as handle:
        handle.write("\n".join(out))
    print("token_codes.hpp: %d tokens, %d..%d" % (len(tokens), first, max(seen)))


if __name__ == "__main__":
    main()
