#pragma once
// satellite/bytecode/token_codes.hpp -- GENERATED by make_token_codes.py
// from REGISTRY.satellite. Do not edit: edit the registry and run the script.
//
// A code below 256 is a character; 256 and up is a token (the author,
// 2026-09-16). is_token() is the one test, and it is the high byte.

#include <cstdint>

namespace satellite004 {
namespace token {

using Code = std::uint16_t;

inline constexpr bool is_token(Code code) { return (code >> 8) != 0; }
inline constexpr bool is_character(Code code) { return (code >> 8) == 0; }
inline constexpr Code family_of(Code code) { return static_cast<Code>(code >> 8); }

// A payload token is followed by a count and then that many codes, which
// are SKIPPED and never classified (REGISTRY.satellite: "EVERY PAYLOAD
// TOKEN CARRIES A COUNT"). The count continues into the next code when it
// is long_count_token, so no literal has a ceiling.
inline constexpr Code kPayloadFamily = 0x09;
inline constexpr bool carries_a_count(Code code) { return family_of(code) == kPayloadFamily; }

inline constexpr Code line_end_token = 0x0100;  // the end of a statement
inline constexpr Code end_of_file_token = 0x0101;  // always the last token
inline constexpr Code error_token = 0x0102;  // the lexer stopped here; an error code follows. The lexer never throws
inline constexpr Code left_brace_token = 0x0200;  // {  opens a body
inline constexpr Code right_brace_token = 0x0201;  // }  closes a body
inline constexpr Code left_parenthesis_token = 0x0202;  // (  opens arguments
inline constexpr Code right_parenthesis_token = 0x0203;  // )  closes arguments
inline constexpr Code left_square_bracket_token = 0x0204;  // [  opens an index
inline constexpr Code right_square_bracket_token = 0x0205;  // ]  closes an index
inline constexpr Code plus_token = 0x0300;  // +
inline constexpr Code minus_token = 0x0301;  // -
inline constexpr Code times_token = 0x0302;  // *
inline constexpr Code divide_token = 0x0303;  // /  only with whitespace on BOTH sides; a touching / is a path
inline constexpr Code modulus_token = 0x0304;  // %
inline constexpr Code assign_token = 0x0400;  // =
inline constexpr Code plus_assign_token = 0x0401;  // +=   QUESTION: 003 DESIGN §6 has one assignment form and no compound
inline constexpr Code minus_assign_token = 0x0402;  // -=   QUESTION: as above
inline constexpr Code times_assign_token = 0x0403;  // *=   QUESTION: as above
inline constexpr Code divide_assign_token = 0x0404;  // /=   QUESTION: as above
inline constexpr Code modulus_assign_token = 0x0405;  // %=   QUESTION: as above
inline constexpr Code equals_token = 0x0500;  // ==
inline constexpr Code not_equals_token = 0x0501;  // !=
inline constexpr Code less_than_token = 0x0502;  // <
inline constexpr Code greater_than_token = 0x0503;  // >
inline constexpr Code less_or_equal_token = 0x0504;  // <=
inline constexpr Code greater_or_equal_token = 0x0505;  // >=
inline constexpr Code and_token = 0x0600;  // &&   QUESTION: 003 DESIGN §13 leaves && and || open, and may spell them as words
inline constexpr Code or_token = 0x0601;  // ||   QUESTION: as above
inline constexpr Code not_token = 0x0602;  // !    QUESTION: §13 leaves open whether ! is the negation
inline constexpr Code bit_and_token = 0x0603;  // &    QUESTION: §6 has no bitwise row; & ends an expression and is reported
inline constexpr Code bit_or_token = 0x0604;  // |    QUESTION: as above
inline constexpr Code bit_exclusive_or_token = 0x0605;  // ^    QUESTION: as above
inline constexpr Code bit_not_token = 0x0606;  // ~    QUESTION: as above
inline constexpr Code shift_left_token = 0x0607;  // <<   QUESTION: 003 DESIGN §5.5 refuses << and >> permanently (the author asked for them 
inline constexpr Code shift_right_token = 0x0608;  // >>   QUESTION: as above
inline constexpr Code bit_run_join_token = 0x0609;  // !!   lays two bit runs end to end; DESIGN §6.6's fifth precedence level, decided 2026-09
inline constexpr Code comma_token = 0x0700;  // ,  between arguments
inline constexpr Code semicolon_token = 0x0701;  // ;  inside a for
inline constexpr Code colon_token = 0x0702;  // :  in for (TYPE name : list), and in a slice
inline constexpr Code namespace_token = 0x0703;  // :: QUESTION: satellite joins every segment with a dot; no program uses ::
inline constexpr Code method_token = 0x0704;  // .  reaches a member; a following ( makes it a call
inline constexpr Code decimal_point_token = 0x0705;  // .  QUESTION: 003's lexer folds 3.14 into one number, dot included
inline constexpr Code word_separator_token = 0x0706;  // .  between a word's numbers: #1.5.1
inline constexpr Code path_separator_token = 0x0707;  // /  QUESTION: a path with a slash is written in quotes, so it travels as characters
inline constexpr Code linux_home_token = 0x0708;  // ~  QUESTION: 003 spells $HOME as a live CHARACTER code, not a token
inline constexpr Code question_token = 0x0709;  // ?  QUESTION: no grammar production accepts it
inline constexpr Code arrow_token = 0x070A;  // -> QUESTION: a return type is satellite.returns(TYPE)
inline constexpr Code double_quote_token = 0x0800;  // "  a string literal starts or ends
inline constexpr Code single_quote_token = 0x0801;  // '  QUESTION: the language has no character type
inline constexpr Code escape_token = 0x0802;  // \  QUESTION: an escape lives inside a string's value, which a token may not
inline constexpr Code comment_token = 0x0803;  // // to the end of the line
inline constexpr Code comment_start_token = 0x0804;  // /* QUESTION: 003 DESIGN §5.6 has no block comment, on purpose
inline constexpr Code comment_end_token = 0x0805;  // */ QUESTION: as above
inline constexpr Code word_number_token = 0x0900;  // a satellite word as its numbers: count, then the numbers
inline constexpr Code name_token = 0x0901;  // a name the user owns: count, then that many character codes
inline constexpr Code number_token = 0x0902;  // a number literal: count, then that many character codes
inline constexpr Code string_token = 0x0903;  // a string literal: count, then that many character codes
inline constexpr Code binary_token = 0x0904;  // b11001100 -- count, then that many character codes
inline constexpr Code hexadecimal_token = 0x0905;  // xFFAAC2985765 -- count, then that many character codes
inline constexpr Code option_token = 0x0906;  // 0#down -- a folded option; count, then that many character codes
inline constexpr Code string_index_token = 0x0907;  // the string at this index in the .sati, once the program carries no text
inline constexpr Code wide_run_token = 0x0908;  // count, then that many characters as their own 16-bit Unicode number
inline constexpr Code wide_run_32_token = 0x0909;  // count, then that many characters as 32 bits each (emoji, rare CJK)
inline constexpr Code long_count_token = 0x090A;  // the count that follows continues in the next code: no literal has a ceiling
inline constexpr Code batch_start_token = 0x0A00;  // opens a batch: these calls may run on one pool thread
inline constexpr Code batch_end_token = 0x0A01;  // closes a batch
inline constexpr Code wait_token = 0x0A02;  // the main thread waits here until everything marked before it has finished
inline constexpr Code batch_size_token = 0x0A03;  // how many commands one batch carries; a count follows
inline constexpr Code extend_token = 0xFFFF;  // the next code carries the token; kept back so an all-ones buffer is never a token

inline constexpr int kTokenCount = 69;

} // namespace token
} // namespace satellite004
