#pragma once
// satellite/bytecode/word_codes.hpp -- GENERATED by make_word_codes.py
// from words/words.tsv. Do not edit: edit the word table and run the script.
//
// EVERY satellite.something.something HAS A 16-BIT CODE, 4096..8191
// (the author, 2026-09-16). 4096 is reserved and no word has it; the words
// start at 4097 and a word's code is 4097 plus its ROW in words.tsv.
//
// TWO NUMBERS, ONE TABLE. A .sat file stores a word as its path numbers
// (1 5 1); the interpreter holds one 16-bit code (4163). They are not the same
// number and cannot be -- a path is a tree of any depth, a code is flat and
// fixed width -- but only the path numbers are maintained. The code is a
// projection of the row, so there is no second set to keep in step.
//
// A CODE IS A FAST PATH AND NEVER A CEILING. code_of() answers 0 -- the
// registry's own "nothing" -- for a word with no code, and the caller then
// writes word_number_token and the numbers, which has no limit.
//
// Generated, so it is exempt from the 300-line rule, like words.def was.

#include "token_codes.hpp"

#include <cstddef>
#include <cstdint>
#include <string_view>
#include <type_traits>

namespace satellite004 {
namespace word {

inline constexpr token::Code kBase = 4096;       // reserved: no word has it
inline constexpr token::Code kFirst = 4097;      // satellite
inline constexpr token::Code kLast = 8191;       // the end of the range
inline constexpr unsigned int kWordsInTable = 421;
inline constexpr unsigned int kMaxDepth = 7;

inline constexpr bool is_word_code(token::Code code) { return code >= kBase && code <= kLast; }

// depth in the top byte, then a byte a number. 0 when it will not pack.
inline constexpr std::uint64_t key_of(const int *numbers, std::size_t depth)
{
    if (depth == 0 || depth > kMaxDepth) return 0;
    std::uint64_t key = static_cast<std::uint64_t>(depth) << 56;
    for (std::size_t i = 0; i < depth; ++i) {
        if (numbers[i] < 0 || numbers[i] > 255) return 0;
        key |= static_cast<std::uint64_t>(numbers[i]) << (48 - i * 8);
    }
    return key;
}

struct KeyedWord { std::uint64_t key; token::Code code; };

// Sorted by key, so code_of() is a binary search and not 364 compares.
inline constexpr KeyedWord kKeyedWords[] = {
    {0x0101000000000000ULL, 4097},  // 1 -- satellite
    {0x0201010000000000ULL, 4098},  // 1 1 -- satellite.include
    {0x0201020000000000ULL, 4102},  // 1 2 -- satellite.capsule
    {0x0201030000000000ULL, 4105},  // 1 3 -- satellite.main
    {0x0201040000000000ULL, 4107},  // 1 4 -- satellite.container
    {0x0201050000000000ULL, 4161},  // 1 5 -- satellite.console
    {0x0201060000000000ULL, 4172},  // 1 6 -- satellite.variable
    {0x0201070000000000ULL, 4284},  // 1 7 -- satellite.random
    {0x0201080000000000ULL, 4302},  // 1 8 -- satellite.file
    {0x0201090000000000ULL, 4309},  // 1 9 -- satellite.time
    {0x02010A0000000000ULL, 4315},  // 1 10 -- satellite.spacesuit
    {0x02010B0000000000ULL, 4317},  // 1 11 -- satellite.protected
    {0x02010C0000000000ULL, 4319},  // 1 12 -- satellite.public
    {0x02010D0000000000ULL, 4321},  // 1 13 -- satellite.statement
    {0x02010E0000000000ULL, 4327},  // 1 14 -- satellite.library
    {0x02010F0000000000ULL, 4388},  // 1 15 -- satellite.return
    {0x0201100000000000ULL, 4392},  // 1 16 -- satellite.analyze
    {0x0201110000000000ULL, 4393},  // 1 17 -- satellite.bool
    {0x0201120000000000ULL, 4397},  // 1 18 -- satellite.directory
    {0x0201130000000000ULL, 4404},  // 1 19 -- satellite.help
    {0x0201140000000000ULL, 4407},  // 1 20 -- satellite.network
    {0x0201150000000000ULL, 4416},  // 1 21 -- satellite.returns
    {0x0201160000000000ULL, 4417},  // 1 22 -- satellite.system
    {0x0201170000000000ULL, 4456},  // 1 23 -- satellite.thread
    {0x0201180000000000ULL, 4459},  // 1 24 -- satellite.constructor
    {0x0201190000000000ULL, 4473},  // 1 25 -- satellite.feedback
    {0x02011A0000000000ULL, 4479},  // 1 26 -- satellite.infinity
    {0x02011B0000000000ULL, 4482},  // 1 27 -- satellite.window
    {0x02011C0000000000ULL, 4514},  // 1 28 -- satellite.namespace
    {0x0301010000000000ULL, 4099},  // 1 1 0 -- satellite.include()
    {0x0301010100000000ULL, 4100},  // 1 1 1 -- satellite.include(satellite)
    {0x0301010200000000ULL, 4101},  // 1 1 2 -- satellite.include(spaceship)
    {0x0301020000000000ULL, 4103},  // 1 2 0 -- satellite.capsule()
    {0x0301020100000000ULL, 4104},  // 1 2 1 -- satellite.capsule.launch
    {0x0301030000000000ULL, 4106},  // 1 3 0 -- satellite.main()
    {0x0301040000000000ULL, 4108},  // 1 4 0 -- satellite.container()
    {0x0301040100000000ULL, 4109},  // 1 4 1 -- satellite.container.map
    {0x0301040200000000ULL, 4121},  // 1 4 2 -- satellite.container.list
    {0x0301040300000000ULL, 4149},  // 1 4 3 -- satellite.container.arguments
    {0x0301040400000000ULL, 4160},  // 1 4 4 -- satellite.container.result
    {0x0301040500000000ULL, 4476},  // 1 4 5 -- satellite.container.index
    {0x0301040600000000ULL, 4477},  // 1 4 6 -- satellite.container.multiple
    {0x0301050000000000ULL, 4162},  // 1 5 0 -- satellite.console()
    {0x0301050100000000ULL, 4163},  // 1 5 1 -- satellite.console.display
    {0x0301050200000000ULL, 4164},  // 1 5 2 -- satellite.console.input()
    {0x0301050300000000ULL, 4165},  // 1 5 3 -- satellite.console.input(prompt)
    {0x0301050400000000ULL, 4166},  // 1 5 4 -- satellite.console.input(prompt, target)
    {0x0301050500000000ULL, 4167},  // 1 5 5 -- satellite.console.typed()
    {0x0301050600000000ULL, 4168},  // 1 5 6 -- satellite.console.width
    {0x0301050700000000ULL, 4169},  // 1 5 7 -- satellite.console.height
    {0x0301050800000000ULL, 4170},  // 1 5 8 -- satellite.console.clear()
    {0x0301050900000000ULL, 4171},  // 1 5 9 -- satellite.console.home()
    {0x0301050A00000000ULL, 4513},  // 1 5 10 -- satellite.console.new(title, width, height)
    {0x0301060000000000ULL, 4173},  // 1 6 0 -- satellite.variable()
    {0x0301060100000000ULL, 4174},  // 1 6 1 -- satellite.variable.string
    {0x0301060200000000ULL, 4198},  // 1 6 2 -- satellite.variable.file
    {0x0301060300000000ULL, 4211},  // 1 6 3 -- satellite.variable.time
    {0x0301060400000000ULL, 4213},  // 1 6 4 -- satellite.variable.number
    {0x0301060500000000ULL, 4235},  // 1 6 5 -- satellite.variable.binary
    {0x0301060600000000ULL, 4249},  // 1 6 6 -- satellite.variable.bool
    {0x0301060700000000ULL, 4250},  // 1 6 7 -- satellite.variable.date
    {0x0301060800000000ULL, 4251},  // 1 6 8 -- satellite.variable.duration
    {0x0301060900000000ULL, 4252},  // 1 6 9 -- satellite.variable.expression
    {0x0301060A00000000ULL, 4253},  // 1 6 10 -- satellite.variable.float
    {0x0301060B00000000ULL, 4260},  // 1 6 11 -- satellite.variable.hex
    {0x0301060C00000000ULL, 4272},  // 1 6 12 -- satellite.variable.network
    {0x0301060D00000000ULL, 4273},  // 1 6 13 -- satellite.variable.thread
    {0x0301060E00000000ULL, 4277},  // 1 6 14 -- satellite.variable.variant
    {0x0301060F00000000ULL, 4283},  // 1 6 15 -- satellite.variable.capsule
    {0x0301061000000000ULL, 4461},  // 1 6 16 -- satellite.variable.percentage
    {0x0301061100000000ULL, 4478},  // 1 6 17 -- satellite.variable.infinity
    {0x0301061200000000ULL, 4481},  // 1 6 18 -- satellite.variable.window
    {0x0301061300000000ULL, 4515},  // 1 6 19 -- satellite.variable.color
    {0x0301061400000000ULL, 4516},  // 1 6 20 -- satellite.variable.fraction
    {0x0301061500000000ULL, 4517},  // 1 6 21 -- satellite.variable.arguments
    {0x0301070000000000ULL, 4285},  // 1 7 0 -- satellite.random()
    {0x0301070100000000ULL, 4286},  // 1 7 1 -- satellite.random.fast()
    {0x0301070200000000ULL, 4287},  // 1 7 2 -- satellite.random.normal()
    {0x0301070300000000ULL, 4288},  // 1 7 3 -- satellite.random.ultra()
    {0x0301070400000000ULL, 4289},  // 1 7 4 -- satellite.random.fast(digits)
    {0x0301070500000000ULL, 4290},  // 1 7 5 -- satellite.random.fast(min, max)
    {0x0301070600000000ULL, 4291},  // 1 7 6 -- satellite.random.fast(min, max, step)
    {0x0301070700000000ULL, 4292},  // 1 7 7 -- satellite.random.normal(digits)
    {0x0301070800000000ULL, 4293},  // 1 7 8 -- satellite.random.normal(min, max)
    {0x0301070900000000ULL, 4294},  // 1 7 9 -- satellite.random.normal(min, max, step)
    {0x0301070A00000000ULL, 4295},  // 1 7 10 -- satellite.random.ultra(digits)
    {0x0301070B00000000ULL, 4296},  // 1 7 11 -- satellite.random.ultra(min, max)
    {0x0301070C00000000ULL, 4297},  // 1 7 12 -- satellite.random.ultra(min, max, step)
    {0x0301070D00000000ULL, 4298},  // 1 7 13 -- satellite.random.seeded(seed)
    {0x0301070E00000000ULL, 4299},  // 1 7 14 -- satellite.random.seeded(min, max)
    {0x0301070F00000000ULL, 4300},  // 1 7 15 -- satellite.random.seeded(min, max, step)
    {0x0301071000000000ULL, 4301},  // 1 7 16 -- satellite.random.seeded()
    {0x0301080000000000ULL, 4303},  // 1 8 0 -- satellite.file()
    {0x0301080100000000ULL, 4304},  // 1 8 1 -- satellite.file.new(path)
    {0x0301080200000000ULL, 4305},  // 1 8 2 -- satellite.file.open(path, mode)
    {0x0301080300000000ULL, 4306},  // 1 8 3 -- satellite.file.clear(path)
    {0x0301080400000000ULL, 4307},  // 1 8 4 -- satellite.file.new(path, mode)
    {0x0301080500000000ULL, 4308},  // 1 8 5 -- satellite.file.exists(path)
    {0x0301080600000000ULL, 4464},  // 1 8 6 -- satellite.file.open(path)
    {0x0301090000000000ULL, 4310},  // 1 9 0 -- satellite.time()
    {0x0301090100000000ULL, 4311},  // 1 9 1 -- satellite.time.now
    {0x0301090200000000ULL, 4312},  // 1 9 2 -- satellite.time.new
    {0x0301090300000000ULL, 4313},  // 1 9 3 -- satellite.time.sleep(n)
    {0x0301090400000000ULL, 4314},  // 1 9 4 -- satellite.time.sleep(n, unit)
    {0x03010A0000000000ULL, 4316},  // 1 10 0 -- satellite.spacesuit()
    {0x03010B0000000000ULL, 4318},  // 1 11 0 -- satellite.protected()
    {0x03010C0000000000ULL, 4320},  // 1 12 0 -- satellite.public()
    {0x03010D0000000000ULL, 4322},  // 1 13 0 -- satellite.statement()
    {0x03010D0100000000ULL, 4323},  // 1 13 1 -- satellite.statement.if
    {0x03010D0200000000ULL, 4324},  // 1 13 2 -- satellite.statement.for
    {0x03010D0300000000ULL, 4325},  // 1 13 3 -- satellite.statement.while
    {0x03010D0400000000ULL, 4326},  // 1 13 4 -- satellite.statement.else
    {0x03010E0000000000ULL, 4328},  // 1 14 0 -- satellite.library()
    {0x03010E0100000000ULL, 4329},  // 1 14 1 -- satellite.library.main
    {0x03010E0200000000ULL, 4382},  // 1 14 2 -- satellite.library.system
    {0x03010F0000000000ULL, 4389},  // 1 15 0 -- satellite.return()
    {0x03010F0100000000ULL, 4390},  // 1 15 1 -- satellite.return(satellite)
    {0x03010F0200000000ULL, 4391},  // 1 15 2 -- satellite.return(value)
    {0x0301110000000000ULL, 4394},  // 1 17 0 -- satellite.bool()
    {0x0301110100000000ULL, 4395},  // 1 17 1 -- satellite.bool.false
    {0x0301110200000000ULL, 4396},  // 1 17 2 -- satellite.bool.true
    {0x0301120000000000ULL, 4398},  // 1 18 0 -- satellite.directory()
    {0x0301120100000000ULL, 4399},  // 1 18 1 -- satellite.directory.change(d)
    {0x0301120200000000ULL, 4400},  // 1 18 2 -- satellite.directory.current()
    {0x0301120300000000ULL, 4401},  // 1 18 3 -- satellite.directory.exists(d)
    {0x0301120400000000ULL, 4402},  // 1 18 4 -- satellite.directory.list()
    {0x0301120500000000ULL, 4403},  // 1 18 5 -- satellite.directory.list(d)
    {0x0301130000000000ULL, 4405},  // 1 19 0 -- satellite.help()
    {0x0301130100000000ULL, 4406},  // 1 19 1 -- satellite.help(x)
    {0x0301140000000000ULL, 4408},  // 1 20 0 -- satellite.network()
    {0x0301140100000000ULL, 4409},  // 1 20 1 -- satellite.network.http(port)
    {0x0301140200000000ULL, 4410},  // 1 20 2 -- satellite.network.https(host, port)
    {0x0301140300000000ULL, 4411},  // 1 20 3 -- satellite.network.new
    {0x0301140400000000ULL, 4412},  // 1 20 4 -- satellite.network.open
    {0x0301140500000000ULL, 4413},  // 1 20 5 -- satellite.network.receive
    {0x0301140600000000ULL, 4414},  // 1 20 6 -- satellite.network.http(host, port)
    {0x0301140700000000ULL, 4415},  // 1 20 7 -- satellite.network.https(port, cert, key)
    {0x0301160000000000ULL, 4418},  // 1 22 0 -- satellite.system()
    {0x0301160100000000ULL, 4419},  // 1 22 1 -- satellite.system.delete(x)
    {0x0301160200000000ULL, 4420},  // 1 22 2 -- satellite.system.environment
    {0x0301160300000000ULL, 4421},  // 1 22 3 -- satellite.system.home
    {0x0301160400000000ULL, 4422},  // 1 22 4 -- satellite.system.memory
    {0x0301160500000000ULL, 4451},  // 1 22 5 -- satellite.system.threshold()
    {0x0301160600000000ULL, 4452},  // 1 22 6 -- satellite.system.threshold(n)
    {0x0301160700000000ULL, 4453},  // 1 22 7 -- satellite.system.persist()
    {0x0301160800000000ULL, 4454},  // 1 22 8 -- satellite.system.persist(x)
    {0x0301160900000000ULL, 4455},  // 1 22 9 -- satellite.system.environment(name)
    {0x0301170000000000ULL, 4457},  // 1 23 0 -- satellite.thread()
    {0x0301170100000000ULL, 4458},  // 1 23 1 -- satellite.thread.new
    {0x0301180000000000ULL, 4460},  // 1 24 0 -- satellite.constructor()
    {0x0301190000000000ULL, 4474},  // 1 25 0 -- satellite.feedback()
    {0x0301190100000000ULL, 4475},  // 1 25 1 -- satellite.feedback(x)
    {0x03011A0000000000ULL, 4480},  // 1 26 0 -- satellite.infinity()
    {0x03011B0100000000ULL, 4483},  // 1 27 1 -- satellite.window.new(title, width, height)
    {0x03011B0200000000ULL, 4484},  // 1 27 2 -- satellite.window.button(text)
    {0x03011B0300000000ULL, 4485},  // 1 27 3 -- satellite.window.label(text)
    {0x03011B0400000000ULL, 4486},  // 1 27 4 -- satellite.window.text_box(text)
    {0x03011B0500000000ULL, 4487},  // 1 27 5 -- satellite.window.text_area(text)
    {0x03011B0600000000ULL, 4488},  // 1 27 6 -- satellite.window.checkbox(text)
    {0x03011B0700000000ULL, 4489},  // 1 27 7 -- satellite.window.switch
    {0x03011B0800000000ULL, 4491},  // 1 27 8 -- satellite.window.slider(least, most)
    {0x03011B0900000000ULL, 4492},  // 1 27 9 -- satellite.window.number_box(least, most)
    {0x03011B0A00000000ULL, 4493},  // 1 27 10 -- satellite.window.progress
    {0x03011B0B00000000ULL, 4495},  // 1 27 11 -- satellite.window.choice(items)
    {0x03011B0C00000000ULL, 4496},  // 1 27 12 -- satellite.window.row
    {0x03011B0D00000000ULL, 4498},  // 1 27 13 -- satellite.window.column
    {0x03011B0E00000000ULL, 4500},  // 1 27 14 -- satellite.window.grid
    {0x03011B0F00000000ULL, 4502},  // 1 27 15 -- satellite.window.picture(path)
    {0x03011B1000000000ULL, 4503},  // 1 27 16 -- satellite.window.scroll
    {0x03011B1100000000ULL, 4505},  // 1 27 17 -- satellite.window.frame(title)
    {0x03011B1200000000ULL, 4506},  // 1 27 18 -- satellite.window.split
    {0x03011B1300000000ULL, 4508},  // 1 27 19 -- satellite.window.menu(title)
    {0x03011B1400000000ULL, 4509},  // 1 27 20 -- satellite.window.canvas(width, height)
    {0x03011B1500000000ULL, 4510},  // 1 27 21 -- satellite.window.tabs
    {0x03011B1600000000ULL, 4512},  // 1 27 22 -- satellite.window.one_of(items)
    {0x0401040100000000ULL, 4110},  // 1 4 1 0 -- satellite.container.map()
    {0x0401040101000000ULL, 4111},  // 1 4 1 1 -- satellite.container.map.set(k, v)
    {0x0401040102000000ULL, 4112},  // 1 4 1 2 -- satellite.container.map.get(k)
    {0x0401040103000000ULL, 4113},  // 1 4 1 3 -- satellite.container.map.has(k)
    {0x0401040104000000ULL, 4114},  // 1 4 1 4 -- satellite.container.map.size
    {0x0401040105000000ULL, 4115},  // 1 4 1 5 -- satellite.container.map.empty
    {0x0401040106000000ULL, 4116},  // 1 4 1 6 -- satellite.container.map.clear
    {0x0401040107000000ULL, 4117},  // 1 4 1 7 -- satellite.container.map.remove(k)
    {0x0401040108000000ULL, 4118},  // 1 4 1 8 -- satellite.container.map.keys
    {0x0401040109000000ULL, 4119},  // 1 4 1 9 -- satellite.container.map.values
    {0x040104010A000000ULL, 4120},  // 1 4 1 10 -- satellite.container.map.search(pattern)
    {0x0401040200000000ULL, 4122},  // 1 4 2 0 -- satellite.container.list()
    {0x0401040201000000ULL, 4123},  // 1 4 2 1 -- satellite.container.list.append
    {0x0401040202000000ULL, 4124},  // 1 4 2 2 -- satellite.container.list.size
    {0x0401040203000000ULL, 4125},  // 1 4 2 3 -- satellite.container.list.sort()
    {0x0401040204000000ULL, 4126},  // 1 4 2 4 -- satellite.container.list.sort(direction)
    {0x0401040205000000ULL, 4127},  // 1 4 2 5 -- satellite.container.list.sort_down()
    {0x0401040206000000ULL, 4128},  // 1 4 2 6 -- satellite.container.list.sort_down(key)
    {0x0401040207000000ULL, 4129},  // 1 4 2 7 -- satellite.container.list.sort_up(key)
    {0x0401040208000000ULL, 4130},  // 1 4 2 8 -- satellite.container.list.contains(x)
    {0x0401040209000000ULL, 4131},  // 1 4 2 9 -- satellite.container.list.index_of(x)
    {0x040104020A000000ULL, 4132},  // 1 4 2 10 -- satellite.container.list.empty
    {0x040104020B000000ULL, 4133},  // 1 4 2 11 -- satellite.container.list.clear
    {0x040104020C000000ULL, 4134},  // 1 4 2 12 -- satellite.container.list.first
    {0x040104020D000000ULL, 4135},  // 1 4 2 13 -- satellite.container.list.last
    {0x040104020E000000ULL, 4136},  // 1 4 2 14 -- satellite.container.list.truncate(n)
    {0x040104020F000000ULL, 4137},  // 1 4 2 15 -- satellite.container.list.reserve(n)
    {0x0401040210000000ULL, 4138},  // 1 4 2 16 -- satellite.container.list.remove_first()
    {0x0401040211000000ULL, 4139},  // 1 4 2 17 -- satellite.container.list.remove_last()
    {0x0401040212000000ULL, 4140},  // 1 4 2 18 -- satellite.container.list.remove_at(n)
    {0x0401040213000000ULL, 4141},  // 1 4 2 19 -- satellite.container.list.remove(x)
    {0x0401040214000000ULL, 4142},  // 1 4 2 20 -- satellite.container.list.insert(n, x)
    {0x0401040215000000ULL, 4143},  // 1 4 2 21 -- satellite.container.list.join(separator)
    {0x0401040216000000ULL, 4144},  // 1 4 2 22 -- satellite.container.list.reverse
    {0x0401040217000000ULL, 4145},  // 1 4 2 23 -- satellite.container.list.sum
    {0x0401040218000000ULL, 4146},  // 1 4 2 24 -- satellite.container.list.max
    {0x0401040219000000ULL, 4147},  // 1 4 2 25 -- satellite.container.list.min
    {0x040104021A000000ULL, 4148},  // 1 4 2 26 -- satellite.container.list.search(pattern)
    {0x0401040301000000ULL, 4150},  // 1 4 3 1 -- satellite.container.arguments.length
    {0x0401040302000000ULL, 4151},  // 1 4 3 2 -- satellite.container.arguments.count
    {0x0401040303000000ULL, 4152},  // 1 4 3 3 -- satellite.container.arguments.keys
    {0x0401040304000000ULL, 4153},  // 1 4 3 4 -- satellite.container.arguments.to_string
    {0x0401040305000000ULL, 4154},  // 1 4 3 5 -- satellite.container.arguments.lines
    {0x0401040306000000ULL, 4155},  // 1 4 3 6 -- satellite.container.arguments.has(k)
    {0x0401040307000000ULL, 4156},  // 1 4 3 7 -- satellite.container.arguments.get(k)
    {0x0401040308000000ULL, 4157},  // 1 4 3 8 -- satellite.container.arguments.first
    {0x0401040309000000ULL, 4158},  // 1 4 3 9 -- satellite.container.arguments.last
    {0x040104030A000000ULL, 4159},  // 1 4 3 10 -- satellite.container.arguments.contains(x)
    {0x0401060100000000ULL, 4175},  // 1 6 1 0 -- satellite.variable.string()
    {0x0401060101000000ULL, 4176},  // 1 6 1 1 -- satellite.variable.string.size
    {0x0401060102000000ULL, 4177},  // 1 6 1 2 -- satellite.variable.string.empty
    {0x0401060103000000ULL, 4178},  // 1 6 1 3 -- satellite.variable.string.find(x)
    {0x0401060104000000ULL, 4179},  // 1 6 1 4 -- satellite.variable.string.contains(x)
    {0x0401060105000000ULL, 4180},  // 1 6 1 5 -- satellite.variable.string.substring(start, end)
    {0x0401060106000000ULL, 4181},  // 1 6 1 6 -- satellite.variable.string.starts_with(x)
    {0x0401060107000000ULL, 4182},  // 1 6 1 7 -- satellite.variable.string.ends_with(x)
    {0x0401060108000000ULL, 4183},  // 1 6 1 8 -- satellite.variable.string.lower
    {0x0401060109000000ULL, 4184},  // 1 6 1 9 -- satellite.variable.string.upper
    {0x040106010A000000ULL, 4185},  // 1 6 1 10 -- satellite.variable.string.split(separator)
    {0x040106010B000000ULL, 4186},  // 1 6 1 11 -- satellite.variable.string.trim
    {0x040106010C000000ULL, 4187},  // 1 6 1 12 -- satellite.variable.string.replace(a, b)
    {0x040106010D000000ULL, 4188},  // 1 6 1 13 -- satellite.variable.string.to_number
    {0x040106010E000000ULL, 4189},  // 1 6 1 14 -- satellite.variable.string.append(x)
    {0x040106010F000000ULL, 4190},  // 1 6 1 15 -- satellite.variable.string.clear
    {0x0401060110000000ULL, 4191},  // 1 6 1 16 -- satellite.variable.string.at(n)
    {0x0401060111000000ULL, 4192},  // 1 6 1 17 -- satellite.variable.string.resolved
    {0x0401060112000000ULL, 4193},  // 1 6 1 18 -- satellite.variable.string(x)
    {0x0401060113000000ULL, 4194},  // 1 6 1 19 -- satellite.variable.string.string
    {0x0401060114000000ULL, 4195},  // 1 6 1 20 -- satellite.variable.string.number
    {0x0401060115000000ULL, 4196},  // 1 6 1 21 -- satellite.variable.string.binary
    {0x0401060116000000ULL, 4197},  // 1 6 1 22 -- satellite.variable.string.hex
    {0x0401060200000000ULL, 4199},  // 1 6 2 0 -- satellite.variable.file()
    {0x0401060201000000ULL, 4200},  // 1 6 2 1 -- satellite.variable.file.new
    {0x0401060202000000ULL, 4201},  // 1 6 2 2 -- satellite.variable.file.open
    {0x0401060203000000ULL, 4202},  // 1 6 2 3 -- satellite.variable.file.read_line
    {0x0401060204000000ULL, 4203},  // 1 6 2 4 -- satellite.variable.file.write_line(s)
    {0x0401060205000000ULL, 4204},  // 1 6 2 5 -- satellite.variable.file.read_all
    {0x0401060206000000ULL, 4205},  // 1 6 2 6 -- satellite.variable.file.close
    {0x0401060207000000ULL, 4206},  // 1 6 2 7 -- satellite.variable.file.exists
    {0x0401060208000000ULL, 4207},  // 1 6 2 8 -- satellite.variable.file.ok
    {0x0401060209000000ULL, 4208},  // 1 6 2 9 -- satellite.variable.file.path
    {0x040106020A000000ULL, 4209},  // 1 6 2 10 -- satellite.variable.file.error
    {0x040106020B000000ULL, 4210},  // 1 6 2 11 -- satellite.variable.file.write(x)
    {0x0401060300000000ULL, 4212},  // 1 6 3 0 -- satellite.variable.time()
    {0x0401060400000000ULL, 4214},  // 1 6 4 0 -- satellite.variable.number()
    {0x0401060401000000ULL, 4215},  // 1 6 4 1 -- satellite.variable.number.shift_left(n)
    {0x0401060402000000ULL, 4216},  // 1 6 4 2 -- satellite.variable.number.max(a, b)
    {0x0401060403000000ULL, 4217},  // 1 6 4 3 -- satellite.variable.number.min(a, b)
    {0x0401060404000000ULL, 4218},  // 1 6 4 4 -- satellite.variable.number.abs(a)
    {0x0401060405000000ULL, 4219},  // 1 6 4 5 -- satellite.variable.number.clamp(a, low, high)
    {0x0401060406000000ULL, 4220},  // 1 6 4 6 -- satellite.variable.number.to_string
    {0x0401060407000000ULL, 4221},  // 1 6 4 7 -- satellite.variable.number.floor
    {0x0401060408000000ULL, 4222},  // 1 6 4 8 -- satellite.variable.number.ceil
    {0x0401060409000000ULL, 4223},  // 1 6 4 9 -- satellite.variable.number.round
    {0x040106040A000000ULL, 4224},  // 1 6 4 10 -- satellite.variable.number.power(a, b)
    {0x040106040B000000ULL, 4225},  // 1 6 4 11 -- satellite.variable.number.shift_right(n)
    {0x040106040C000000ULL, 4226},  // 1 6 4 12 -- satellite.variable.number.modulus(a, b)
    {0x040106040D000000ULL, 4227},  // 1 6 4 13 -- satellite.variable.number.truncate(a)
    {0x040106040E000000ULL, 4228},  // 1 6 4 14 -- satellite.variable.number.sqrt(a)
    {0x040106040F000000ULL, 4229},  // 1 6 4 15 -- satellite.variable.number.digits
    {0x0401060410000000ULL, 4230},  // 1 6 4 16 -- satellite.variable.number(x)
    {0x0401060411000000ULL, 4231},  // 1 6 4 17 -- satellite.variable.number.string
    {0x0401060412000000ULL, 4232},  // 1 6 4 18 -- satellite.variable.number.number
    {0x0401060413000000ULL, 4233},  // 1 6 4 19 -- satellite.variable.number.binary
    {0x0401060414000000ULL, 4234},  // 1 6 4 20 -- satellite.variable.number.hex
    {0x0401060500000000ULL, 4236},  // 1 6 5 0 -- satellite.variable.binary()
    {0x0401060501000000ULL, 4237},  // 1 6 5 1 -- satellite.variable.binary.to_number
    {0x0401060502000000ULL, 4238},  // 1 6 5 2 -- satellite.variable.binary.width
    {0x0401060503000000ULL, 4239},  // 1 6 5 3 -- satellite.variable.binary.to_string
    {0x0401060504000000ULL, 4240},  // 1 6 5 4 -- satellite.variable.binary.as_number
    {0x0401060505000000ULL, 4241},  // 1 6 5 5 -- satellite.variable.binary.digits
    {0x0401060506000000ULL, 4242},  // 1 6 5 6 -- satellite.variable.binary.to_hex
    {0x0401060507000000ULL, 4243},  // 1 6 5 7 -- satellite.variable.binary(x)
    {0x0401060508000000ULL, 4244},  // 1 6 5 8 -- satellite.variable.binary.string
    {0x0401060509000000ULL, 4245},  // 1 6 5 9 -- satellite.variable.binary.number
    {0x040106050A000000ULL, 4246},  // 1 6 5 10 -- satellite.variable.binary.binary
    {0x040106050B000000ULL, 4247},  // 1 6 5 11 -- satellite.variable.binary.hex
    {0x040106050C000000ULL, 4248},  // 1 6 5 12 -- satellite.variable.binary.clear
    {0x0401060A00000000ULL, 4254},  // 1 6 10 0 -- satellite.variable.float()
    {0x0401060A01000000ULL, 4255},  // 1 6 10 1 -- satellite.variable.float.to_string
    {0x0401060A02000000ULL, 4256},  // 1 6 10 2 -- satellite.variable.float.string
    {0x0401060A03000000ULL, 4257},  // 1 6 10 3 -- satellite.variable.float.number
    {0x0401060A04000000ULL, 4258},  // 1 6 10 4 -- satellite.variable.float.binary
    {0x0401060A05000000ULL, 4259},  // 1 6 10 5 -- satellite.variable.float.hex
    {0x0401060B00000000ULL, 4261},  // 1 6 11 0 -- satellite.variable.hex()
    {0x0401060B01000000ULL, 4262},  // 1 6 11 1 -- satellite.variable.hex.to_number
    {0x0401060B02000000ULL, 4263},  // 1 6 11 2 -- satellite.variable.hex.width
    {0x0401060B03000000ULL, 4264},  // 1 6 11 3 -- satellite.variable.hex.to_string
    {0x0401060B04000000ULL, 4265},  // 1 6 11 4 -- satellite.variable.hex.digits
    {0x0401060B05000000ULL, 4266},  // 1 6 11 5 -- satellite.variable.hex.to_binary
    {0x0401060B06000000ULL, 4267},  // 1 6 11 6 -- satellite.variable.hex(x)
    {0x0401060B07000000ULL, 4268},  // 1 6 11 7 -- satellite.variable.hex.string
    {0x0401060B08000000ULL, 4269},  // 1 6 11 8 -- satellite.variable.hex.number
    {0x0401060B09000000ULL, 4270},  // 1 6 11 9 -- satellite.variable.hex.binary
    {0x0401060B0A000000ULL, 4271},  // 1 6 11 10 -- satellite.variable.hex.hex
    {0x0401060D00000000ULL, 4274},  // 1 6 13 0 -- satellite.variable.thread()
    {0x0401060D01000000ULL, 4275},  // 1 6 13 1 -- satellite.variable.thread.start()
    {0x0401060D02000000ULL, 4276},  // 1 6 13 2 -- satellite.variable.thread.join()
    {0x0401060E00000000ULL, 4278},  // 1 6 14 0 -- satellite.variable.variant()
    {0x0401060E01000000ULL, 4279},  // 1 6 14 1 -- satellite.variable.variant.holding
    {0x0401060E02000000ULL, 4280},  // 1 6 14 2 -- satellite.variable.variant.holds(x)
    {0x0401060E03000000ULL, 4281},  // 1 6 14 3 -- satellite.variable.variant.held
    {0x0401060E04000000ULL, 4282},  // 1 6 14 4 -- satellite.variable.variant.clear
    {0x04010E0100000000ULL, 4330},  // 1 14 1 0 -- satellite.library.main()
    {0x04010E0101000000ULL, 4331},  // 1 14 1 1 -- satellite.library.main.arguments
    {0x04010E0200000000ULL, 4383},  // 1 14 2 0 -- satellite.library.system()
    {0x04010E0201000000ULL, 4384},  // 1 14 2 1 -- satellite.library.system.division_digits
    {0x04010E0202000000ULL, 4385},  // 1 14 2 2 -- satellite.library.system.max_depth
    {0x04010E0203000000ULL, 4386},  // 1 14 2 3 -- satellite.library.system.min_free_mb
    {0x04010E0204000000ULL, 4387},  // 1 14 2 4 -- satellite.library.system.float_digits
    {0x0401160400000000ULL, 4423},  // 1 22 4 0 -- satellite.system.memory()
    {0x0401160401000000ULL, 4424},  // 1 22 4 1 -- satellite.system.memory.bit
    {0x0401160402000000ULL, 4425},  // 1 22 4 2 -- satellite.system.memory.frequency
    {0x0401160403000000ULL, 4426},  // 1 22 4 3 -- satellite.system.memory.main()
    {0x0401160404000000ULL, 4427},  // 1 22 4 4 -- satellite.system.memory.swap
    {0x0401160405000000ULL, 4436},  // 1 22 4 5 -- satellite.system.memory.this
    {0x0401160406000000ULL, 4444},  // 1 22 4 6 -- satellite.system.memory.free()
    {0x0401160407000000ULL, 4445},  // 1 22 4 7 -- satellite.system.memory.total()
    {0x0401160408000000ULL, 4446},  // 1 22 4 8 -- satellite.system.memory.used()
    {0x0401160409000000ULL, 4447},  // 1 22 4 9 -- satellite.system.memory.main(unit)
    {0x040116040A000000ULL, 4448},  // 1 22 4 10 -- satellite.system.memory.free(unit)
    {0x040116040B000000ULL, 4449},  // 1 22 4 11 -- satellite.system.memory.total(unit)
    {0x040116040C000000ULL, 4450},  // 1 22 4 12 -- satellite.system.memory.used(unit)
    {0x04011B0700000000ULL, 4490},  // 1 27 7 0 -- satellite.window.switch()
    {0x04011B0A00000000ULL, 4494},  // 1 27 10 0 -- satellite.window.progress()
    {0x04011B0C00000000ULL, 4497},  // 1 27 12 0 -- satellite.window.row()
    {0x04011B0D00000000ULL, 4499},  // 1 27 13 0 -- satellite.window.column()
    {0x04011B0E00000000ULL, 4501},  // 1 27 14 0 -- satellite.window.grid()
    {0x04011B1000000000ULL, 4504},  // 1 27 16 0 -- satellite.window.scroll()
    {0x04011B1200000000ULL, 4507},  // 1 27 18 0 -- satellite.window.split()
    {0x04011B1500000000ULL, 4511},  // 1 27 21 0 -- satellite.window.tabs()
    {0x05010E0101000000ULL, 4332},  // 1 14 1 1 0 -- satellite.library.main.arguments()
    {0x05010E0101010000ULL, 4333},  // 1 14 1 1 1 -- satellite.library.main.arguments.machine
    {0x05010E0101020000ULL, 4342},  // 1 14 1 1 2 -- satellite.library.main.arguments.memory
    {0x05010E0101030000ULL, 4345},  // 1 14 1 1 3 -- satellite.library.main.arguments.username
    {0x05010E0101040000ULL, 4346},  // 1 14 1 1 4 -- satellite.library.main.arguments.system
    {0x05010E0101050000ULL, 4355},  // 1 14 1 1 5 -- satellite.library.main.arguments.build
    {0x05010E0101060000ULL, 4365},  // 1 14 1 1 6 -- satellite.library.main.arguments.interpreter
    {0x05010E0101070000ULL, 4370},  // 1 14 1 1 7 -- satellite.library.main.arguments.process
    {0x05010E0101080000ULL, 4374},  // 1 14 1 1 8 -- satellite.library.main.arguments.session
    {0x05010E0101090000ULL, 4381},  // 1 14 1 1 9 -- satellite.library.main.arguments.length
    {0x05010E01010A0000ULL, 4462},  // 1 14 1 1 10 -- satellite.library.main.arguments.access
    {0x05010E01010B0000ULL, 4463},  // 1 14 1 1 11 -- satellite.library.main.arguments.history
    {0x05010E01010C0000ULL, 4467},  // 1 14 1 1 12 -- satellite.library.main.arguments.directory
    {0x05010E01010D0000ULL, 4468},  // 1 14 1 1 13 -- satellite.library.main.arguments.cores
    {0x05010E01010E0000ULL, 4469},  // 1 14 1 1 14 -- satellite.library.main.arguments.threads
    {0x05010E01010F0000ULL, 4470},  // 1 14 1 1 15 -- satellite.library.main.arguments.user
    {0x05010E0101100000ULL, 4471},  // 1 14 1 1 16 -- satellite.library.main.arguments.ram
    {0x05010E0101110000ULL, 4472},  // 1 14 1 1 17 -- satellite.library.main.arguments.dir
    {0x0501160404000000ULL, 4428},  // 1 22 4 4 0 -- satellite.system.memory.swap()
    {0x0501160404010000ULL, 4429},  // 1 22 4 4 1 -- satellite.system.memory.swap.free()
    {0x0501160404020000ULL, 4430},  // 1 22 4 4 2 -- satellite.system.memory.swap.total()
    {0x0501160404030000ULL, 4431},  // 1 22 4 4 3 -- satellite.system.memory.swap.used
    {0x0501160404040000ULL, 4432},  // 1 22 4 4 4 -- satellite.system.memory.swap.free(unit)
    {0x0501160404050000ULL, 4433},  // 1 22 4 4 5 -- satellite.system.memory.swap.total(unit)
    {0x0501160404060000ULL, 4434},  // 1 22 4 4 6 -- satellite.system.memory.swap(unit)
    {0x0501160404070000ULL, 4435},  // 1 22 4 4 7 -- satellite.system.memory.swap.used(unit)
    {0x0501160405000000ULL, 4437},  // 1 22 4 5 0 -- satellite.system.memory.this()
    {0x0501160405010000ULL, 4438},  // 1 22 4 5 1 -- satellite.system.memory.this.available()
    {0x0501160405020000ULL, 4439},  // 1 22 4 5 2 -- satellite.system.memory.this.free()
    {0x0501160405030000ULL, 4440},  // 1 22 4 5 3 -- satellite.system.memory.this.used
    {0x0501160405040000ULL, 4441},  // 1 22 4 5 4 -- satellite.system.memory.this.available(unit)
    {0x0501160405050000ULL, 4442},  // 1 22 4 5 5 -- satellite.system.memory.this.free(unit)
    {0x0501160405060000ULL, 4443},  // 1 22 4 5 6 -- satellite.system.memory.this.used(unit)
    {0x06010E0101010000ULL, 4334},  // 1 14 1 1 1 0 -- satellite.library.main.arguments.machine()
    {0x06010E0101010100ULL, 4335},  // 1 14 1 1 1 1 -- satellite.library.main.arguments.machine.cores
    {0x06010E0101010200ULL, 4336},  // 1 14 1 1 1 2 -- satellite.library.main.arguments.machine.cpu
    {0x06010E0101010300ULL, 4337},  // 1 14 1 1 1 3 -- satellite.library.main.arguments.machine.threads
    {0x06010E0101010400ULL, 4338},  // 1 14 1 1 1 4 -- satellite.library.main.arguments.machine.architecture
    {0x06010E0101010500ULL, 4339},  // 1 14 1 1 1 5 -- satellite.library.main.arguments.machine.byte_order
    {0x06010E0101010600ULL, 4340},  // 1 14 1 1 1 6 -- satellite.library.main.arguments.machine.page_size
    {0x06010E0101010700ULL, 4341},  // 1 14 1 1 1 7 -- satellite.library.main.arguments.machine.pointer_bits
    {0x06010E0101020000ULL, 4343},  // 1 14 1 1 2 0 -- satellite.library.main.arguments.memory()
    {0x06010E0101020100ULL, 4344},  // 1 14 1 1 2 1 -- satellite.library.main.arguments.memory.total
    {0x06010E0101020200ULL, 4465},  // 1 14 1 1 2 2 -- satellite.library.main.arguments.memory.free
    {0x06010E0101020300ULL, 4466},  // 1 14 1 1 2 3 -- satellite.library.main.arguments.memory.used
    {0x06010E0101040000ULL, 4347},  // 1 14 1 1 4 0 -- satellite.library.main.arguments.system()
    {0x06010E0101040100ULL, 4348},  // 1 14 1 1 4 1 -- satellite.library.main.arguments.system.name
    {0x06010E0101040200ULL, 4349},  // 1 14 1 1 4 2 -- satellite.library.main.arguments.system.kernel
    {0x06010E0101040300ULL, 4350},  // 1 14 1 1 4 3 -- satellite.library.main.arguments.system.kernel_version
    {0x06010E0101040400ULL, 4351},  // 1 14 1 1 4 4 -- satellite.library.main.arguments.system.distribution
    {0x06010E0101040500ULL, 4352},  // 1 14 1 1 4 5 -- satellite.library.main.arguments.system.distribution_id
    {0x06010E0101040600ULL, 4353},  // 1 14 1 1 4 6 -- satellite.library.main.arguments.system.distribution_version
    {0x06010E0101040700ULL, 4354},  // 1 14 1 1 4 7 -- satellite.library.main.arguments.system.hostname
    {0x06010E0101050000ULL, 4356},  // 1 14 1 1 5 0 -- satellite.library.main.arguments.build()
    {0x06010E0101050100ULL, 4357},  // 1 14 1 1 5 1 -- satellite.library.main.arguments.build.compiler
    {0x06010E0101050200ULL, 4358},  // 1 14 1 1 5 2 -- satellite.library.main.arguments.build.compiler_version
    {0x06010E0101050300ULL, 4359},  // 1 14 1 1 5 3 -- satellite.library.main.arguments.build.standard
    {0x06010E0101050400ULL, 4360},  // 1 14 1 1 5 4 -- satellite.library.main.arguments.build.flags
    {0x06010E0101050500ULL, 4361},  // 1 14 1 1 5 5 -- satellite.library.main.arguments.build.make
    {0x06010E0101050600ULL, 4362},  // 1 14 1 1 5 6 -- satellite.library.main.arguments.build.standard_library
    {0x06010E0101050700ULL, 4363},  // 1 14 1 1 5 7 -- satellite.library.main.arguments.build.c_library
    {0x06010E0101050800ULL, 4364},  // 1 14 1 1 5 8 -- satellite.library.main.arguments.build.built
    {0x06010E0101060000ULL, 4366},  // 1 14 1 1 6 0 -- satellite.library.main.arguments.interpreter()
    {0x06010E0101060100ULL, 4367},  // 1 14 1 1 6 1 -- satellite.library.main.arguments.interpreter.version
    {0x06010E0101060200ULL, 4368},  // 1 14 1 1 6 2 -- satellite.library.main.arguments.interpreter.library_path
    {0x06010E0101060300ULL, 4369},  // 1 14 1 1 6 3 -- satellite.library.main.arguments.interpreter.library_path_source
    {0x06010E0101070000ULL, 4371},  // 1 14 1 1 7 0 -- satellite.library.main.arguments.process()
    {0x06010E0101070100ULL, 4372},  // 1 14 1 1 7 1 -- satellite.library.main.arguments.process.id
    {0x06010E0101070200ULL, 4373},  // 1 14 1 1 7 2 -- satellite.library.main.arguments.process.parent
    {0x06010E0101080000ULL, 4375},  // 1 14 1 1 8 0 -- satellite.library.main.arguments.session()
    {0x06010E0101080100ULL, 4376},  // 1 14 1 1 8 1 -- satellite.library.main.arguments.session.shell
    {0x06010E0101080200ULL, 4377},  // 1 14 1 1 8 2 -- satellite.library.main.arguments.session.terminal
    {0x06010E0101080300ULL, 4378},  // 1 14 1 1 8 3 -- satellite.library.main.arguments.session.language
    {0x06010E0101080400ULL, 4379},  // 1 14 1 1 8 4 -- satellite.library.main.arguments.session.home
    {0x06010E0101080500ULL, 4380},  // 1 14 1 1 8 5 -- satellite.library.main.arguments.session.directory
};

inline constexpr std::size_t kKeyedWordCount = sizeof kKeyedWords / sizeof kKeyedWords[0];

// The numbers and the spelling behind each code, indexed by code - kFirst.
struct WordFacts { const char *path; int numbers[kMaxDepth]; unsigned int depth; };

inline constexpr WordFacts kWordFacts[] = {
    {"satellite", {1, 0, 0, 0, 0, 0, 0}, 1},
    {"satellite.include", {1, 1, 0, 0, 0, 0, 0}, 2},
    {"satellite.include()", {1, 1, 0, 0, 0, 0, 0}, 3},
    {"satellite.include(satellite)", {1, 1, 1, 0, 0, 0, 0}, 3},
    {"satellite.include(spaceship)", {1, 1, 2, 0, 0, 0, 0}, 3},
    {"satellite.capsule", {1, 2, 0, 0, 0, 0, 0}, 2},
    {"satellite.capsule()", {1, 2, 0, 0, 0, 0, 0}, 3},
    {"satellite.capsule.launch", {1, 2, 1, 0, 0, 0, 0}, 3},
    {"satellite.main", {1, 3, 0, 0, 0, 0, 0}, 2},
    {"satellite.main()", {1, 3, 0, 0, 0, 0, 0}, 3},
    {"satellite.container", {1, 4, 0, 0, 0, 0, 0}, 2},
    {"satellite.container()", {1, 4, 0, 0, 0, 0, 0}, 3},
    {"satellite.container.map", {1, 4, 1, 0, 0, 0, 0}, 3},
    {"satellite.container.map()", {1, 4, 1, 0, 0, 0, 0}, 4},
    {"satellite.container.map.set(k, v)", {1, 4, 1, 1, 0, 0, 0}, 4},
    {"satellite.container.map.get(k)", {1, 4, 1, 2, 0, 0, 0}, 4},
    {"satellite.container.map.has(k)", {1, 4, 1, 3, 0, 0, 0}, 4},
    {"satellite.container.map.size", {1, 4, 1, 4, 0, 0, 0}, 4},
    {"satellite.container.map.empty", {1, 4, 1, 5, 0, 0, 0}, 4},
    {"satellite.container.map.clear", {1, 4, 1, 6, 0, 0, 0}, 4},
    {"satellite.container.map.remove(k)", {1, 4, 1, 7, 0, 0, 0}, 4},
    {"satellite.container.map.keys", {1, 4, 1, 8, 0, 0, 0}, 4},
    {"satellite.container.map.values", {1, 4, 1, 9, 0, 0, 0}, 4},
    {"satellite.container.map.search(pattern)", {1, 4, 1, 10, 0, 0, 0}, 4},
    {"satellite.container.list", {1, 4, 2, 0, 0, 0, 0}, 3},
    {"satellite.container.list()", {1, 4, 2, 0, 0, 0, 0}, 4},
    {"satellite.container.list.append", {1, 4, 2, 1, 0, 0, 0}, 4},
    {"satellite.container.list.size", {1, 4, 2, 2, 0, 0, 0}, 4},
    {"satellite.container.list.sort()", {1, 4, 2, 3, 0, 0, 0}, 4},
    {"satellite.container.list.sort(direction)", {1, 4, 2, 4, 0, 0, 0}, 4},
    {"satellite.container.list.sort_down()", {1, 4, 2, 5, 0, 0, 0}, 4},
    {"satellite.container.list.sort_down(key)", {1, 4, 2, 6, 0, 0, 0}, 4},
    {"satellite.container.list.sort_up(key)", {1, 4, 2, 7, 0, 0, 0}, 4},
    {"satellite.container.list.contains(x)", {1, 4, 2, 8, 0, 0, 0}, 4},
    {"satellite.container.list.index_of(x)", {1, 4, 2, 9, 0, 0, 0}, 4},
    {"satellite.container.list.empty", {1, 4, 2, 10, 0, 0, 0}, 4},
    {"satellite.container.list.clear", {1, 4, 2, 11, 0, 0, 0}, 4},
    {"satellite.container.list.first", {1, 4, 2, 12, 0, 0, 0}, 4},
    {"satellite.container.list.last", {1, 4, 2, 13, 0, 0, 0}, 4},
    {"satellite.container.list.truncate(n)", {1, 4, 2, 14, 0, 0, 0}, 4},
    {"satellite.container.list.reserve(n)", {1, 4, 2, 15, 0, 0, 0}, 4},
    {"satellite.container.list.remove_first()", {1, 4, 2, 16, 0, 0, 0}, 4},
    {"satellite.container.list.remove_last()", {1, 4, 2, 17, 0, 0, 0}, 4},
    {"satellite.container.list.remove_at(n)", {1, 4, 2, 18, 0, 0, 0}, 4},
    {"satellite.container.list.remove(x)", {1, 4, 2, 19, 0, 0, 0}, 4},
    {"satellite.container.list.insert(n, x)", {1, 4, 2, 20, 0, 0, 0}, 4},
    {"satellite.container.list.join(separator)", {1, 4, 2, 21, 0, 0, 0}, 4},
    {"satellite.container.list.reverse", {1, 4, 2, 22, 0, 0, 0}, 4},
    {"satellite.container.list.sum", {1, 4, 2, 23, 0, 0, 0}, 4},
    {"satellite.container.list.max", {1, 4, 2, 24, 0, 0, 0}, 4},
    {"satellite.container.list.min", {1, 4, 2, 25, 0, 0, 0}, 4},
    {"satellite.container.list.search(pattern)", {1, 4, 2, 26, 0, 0, 0}, 4},
    {"satellite.container.arguments", {1, 4, 3, 0, 0, 0, 0}, 3},
    {"satellite.container.arguments.length", {1, 4, 3, 1, 0, 0, 0}, 4},
    {"satellite.container.arguments.count", {1, 4, 3, 2, 0, 0, 0}, 4},
    {"satellite.container.arguments.keys", {1, 4, 3, 3, 0, 0, 0}, 4},
    {"satellite.container.arguments.to_string", {1, 4, 3, 4, 0, 0, 0}, 4},
    {"satellite.container.arguments.lines", {1, 4, 3, 5, 0, 0, 0}, 4},
    {"satellite.container.arguments.has(k)", {1, 4, 3, 6, 0, 0, 0}, 4},
    {"satellite.container.arguments.get(k)", {1, 4, 3, 7, 0, 0, 0}, 4},
    {"satellite.container.arguments.first", {1, 4, 3, 8, 0, 0, 0}, 4},
    {"satellite.container.arguments.last", {1, 4, 3, 9, 0, 0, 0}, 4},
    {"satellite.container.arguments.contains(x)", {1, 4, 3, 10, 0, 0, 0}, 4},
    {"satellite.container.result", {1, 4, 4, 0, 0, 0, 0}, 3},
    {"satellite.console", {1, 5, 0, 0, 0, 0, 0}, 2},
    {"satellite.console()", {1, 5, 0, 0, 0, 0, 0}, 3},
    {"satellite.console.display", {1, 5, 1, 0, 0, 0, 0}, 3},
    {"satellite.console.input()", {1, 5, 2, 0, 0, 0, 0}, 3},
    {"satellite.console.input(prompt)", {1, 5, 3, 0, 0, 0, 0}, 3},
    {"satellite.console.input(prompt, target)", {1, 5, 4, 0, 0, 0, 0}, 3},
    {"satellite.console.typed()", {1, 5, 5, 0, 0, 0, 0}, 3},
    {"satellite.console.width", {1, 5, 6, 0, 0, 0, 0}, 3},
    {"satellite.console.height", {1, 5, 7, 0, 0, 0, 0}, 3},
    {"satellite.console.clear()", {1, 5, 8, 0, 0, 0, 0}, 3},
    {"satellite.console.home()", {1, 5, 9, 0, 0, 0, 0}, 3},
    {"satellite.variable", {1, 6, 0, 0, 0, 0, 0}, 2},
    {"satellite.variable()", {1, 6, 0, 0, 0, 0, 0}, 3},
    {"satellite.variable.string", {1, 6, 1, 0, 0, 0, 0}, 3},
    {"satellite.variable.string()", {1, 6, 1, 0, 0, 0, 0}, 4},
    {"satellite.variable.string.size", {1, 6, 1, 1, 0, 0, 0}, 4},
    {"satellite.variable.string.empty", {1, 6, 1, 2, 0, 0, 0}, 4},
    {"satellite.variable.string.find(x)", {1, 6, 1, 3, 0, 0, 0}, 4},
    {"satellite.variable.string.contains(x)", {1, 6, 1, 4, 0, 0, 0}, 4},
    {"satellite.variable.string.substring(start, end)", {1, 6, 1, 5, 0, 0, 0}, 4},
    {"satellite.variable.string.starts_with(x)", {1, 6, 1, 6, 0, 0, 0}, 4},
    {"satellite.variable.string.ends_with(x)", {1, 6, 1, 7, 0, 0, 0}, 4},
    {"satellite.variable.string.lower", {1, 6, 1, 8, 0, 0, 0}, 4},
    {"satellite.variable.string.upper", {1, 6, 1, 9, 0, 0, 0}, 4},
    {"satellite.variable.string.split(separator)", {1, 6, 1, 10, 0, 0, 0}, 4},
    {"satellite.variable.string.trim", {1, 6, 1, 11, 0, 0, 0}, 4},
    {"satellite.variable.string.replace(a, b)", {1, 6, 1, 12, 0, 0, 0}, 4},
    {"satellite.variable.string.to_number", {1, 6, 1, 13, 0, 0, 0}, 4},
    {"satellite.variable.string.append(x)", {1, 6, 1, 14, 0, 0, 0}, 4},
    {"satellite.variable.string.clear", {1, 6, 1, 15, 0, 0, 0}, 4},
    {"satellite.variable.string.at(n)", {1, 6, 1, 16, 0, 0, 0}, 4},
    {"satellite.variable.string.resolved", {1, 6, 1, 17, 0, 0, 0}, 4},
    {"satellite.variable.string(x)", {1, 6, 1, 18, 0, 0, 0}, 4},
    {"satellite.variable.string.string", {1, 6, 1, 19, 0, 0, 0}, 4},
    {"satellite.variable.string.number", {1, 6, 1, 20, 0, 0, 0}, 4},
    {"satellite.variable.string.binary", {1, 6, 1, 21, 0, 0, 0}, 4},
    {"satellite.variable.string.hex", {1, 6, 1, 22, 0, 0, 0}, 4},
    {"satellite.variable.file", {1, 6, 2, 0, 0, 0, 0}, 3},
    {"satellite.variable.file()", {1, 6, 2, 0, 0, 0, 0}, 4},
    {"satellite.variable.file.new", {1, 6, 2, 1, 0, 0, 0}, 4},
    {"satellite.variable.file.open", {1, 6, 2, 2, 0, 0, 0}, 4},
    {"satellite.variable.file.read_line", {1, 6, 2, 3, 0, 0, 0}, 4},
    {"satellite.variable.file.write_line(s)", {1, 6, 2, 4, 0, 0, 0}, 4},
    {"satellite.variable.file.read_all", {1, 6, 2, 5, 0, 0, 0}, 4},
    {"satellite.variable.file.close", {1, 6, 2, 6, 0, 0, 0}, 4},
    {"satellite.variable.file.exists", {1, 6, 2, 7, 0, 0, 0}, 4},
    {"satellite.variable.file.ok", {1, 6, 2, 8, 0, 0, 0}, 4},
    {"satellite.variable.file.path", {1, 6, 2, 9, 0, 0, 0}, 4},
    {"satellite.variable.file.error", {1, 6, 2, 10, 0, 0, 0}, 4},
    {"satellite.variable.file.write(x)", {1, 6, 2, 11, 0, 0, 0}, 4},
    {"satellite.variable.time", {1, 6, 3, 0, 0, 0, 0}, 3},
    {"satellite.variable.time()", {1, 6, 3, 0, 0, 0, 0}, 4},
    {"satellite.variable.number", {1, 6, 4, 0, 0, 0, 0}, 3},
    {"satellite.variable.number()", {1, 6, 4, 0, 0, 0, 0}, 4},
    {"satellite.variable.number.shift_left(n)", {1, 6, 4, 1, 0, 0, 0}, 4},
    {"satellite.variable.number.max(a, b)", {1, 6, 4, 2, 0, 0, 0}, 4},
    {"satellite.variable.number.min(a, b)", {1, 6, 4, 3, 0, 0, 0}, 4},
    {"satellite.variable.number.abs(a)", {1, 6, 4, 4, 0, 0, 0}, 4},
    {"satellite.variable.number.clamp(a, low, high)", {1, 6, 4, 5, 0, 0, 0}, 4},
    {"satellite.variable.number.to_string", {1, 6, 4, 6, 0, 0, 0}, 4},
    {"satellite.variable.number.floor", {1, 6, 4, 7, 0, 0, 0}, 4},
    {"satellite.variable.number.ceil", {1, 6, 4, 8, 0, 0, 0}, 4},
    {"satellite.variable.number.round", {1, 6, 4, 9, 0, 0, 0}, 4},
    {"satellite.variable.number.power(a, b)", {1, 6, 4, 10, 0, 0, 0}, 4},
    {"satellite.variable.number.shift_right(n)", {1, 6, 4, 11, 0, 0, 0}, 4},
    {"satellite.variable.number.modulus(a, b)", {1, 6, 4, 12, 0, 0, 0}, 4},
    {"satellite.variable.number.truncate(a)", {1, 6, 4, 13, 0, 0, 0}, 4},
    {"satellite.variable.number.sqrt(a)", {1, 6, 4, 14, 0, 0, 0}, 4},
    {"satellite.variable.number.digits", {1, 6, 4, 15, 0, 0, 0}, 4},
    {"satellite.variable.number(x)", {1, 6, 4, 16, 0, 0, 0}, 4},
    {"satellite.variable.number.string", {1, 6, 4, 17, 0, 0, 0}, 4},
    {"satellite.variable.number.number", {1, 6, 4, 18, 0, 0, 0}, 4},
    {"satellite.variable.number.binary", {1, 6, 4, 19, 0, 0, 0}, 4},
    {"satellite.variable.number.hex", {1, 6, 4, 20, 0, 0, 0}, 4},
    {"satellite.variable.binary", {1, 6, 5, 0, 0, 0, 0}, 3},
    {"satellite.variable.binary()", {1, 6, 5, 0, 0, 0, 0}, 4},
    {"satellite.variable.binary.to_number", {1, 6, 5, 1, 0, 0, 0}, 4},
    {"satellite.variable.binary.width", {1, 6, 5, 2, 0, 0, 0}, 4},
    {"satellite.variable.binary.to_string", {1, 6, 5, 3, 0, 0, 0}, 4},
    {"satellite.variable.binary.as_number", {1, 6, 5, 4, 0, 0, 0}, 4},
    {"satellite.variable.binary.digits", {1, 6, 5, 5, 0, 0, 0}, 4},
    {"satellite.variable.binary.to_hex", {1, 6, 5, 6, 0, 0, 0}, 4},
    {"satellite.variable.binary(x)", {1, 6, 5, 7, 0, 0, 0}, 4},
    {"satellite.variable.binary.string", {1, 6, 5, 8, 0, 0, 0}, 4},
    {"satellite.variable.binary.number", {1, 6, 5, 9, 0, 0, 0}, 4},
    {"satellite.variable.binary.binary", {1, 6, 5, 10, 0, 0, 0}, 4},
    {"satellite.variable.binary.hex", {1, 6, 5, 11, 0, 0, 0}, 4},
    {"satellite.variable.binary.clear", {1, 6, 5, 12, 0, 0, 0}, 4},
    {"satellite.variable.bool", {1, 6, 6, 0, 0, 0, 0}, 3},
    {"satellite.variable.date", {1, 6, 7, 0, 0, 0, 0}, 3},
    {"satellite.variable.duration", {1, 6, 8, 0, 0, 0, 0}, 3},
    {"satellite.variable.expression", {1, 6, 9, 0, 0, 0, 0}, 3},
    {"satellite.variable.float", {1, 6, 10, 0, 0, 0, 0}, 3},
    {"satellite.variable.float()", {1, 6, 10, 0, 0, 0, 0}, 4},
    {"satellite.variable.float.to_string", {1, 6, 10, 1, 0, 0, 0}, 4},
    {"satellite.variable.float.string", {1, 6, 10, 2, 0, 0, 0}, 4},
    {"satellite.variable.float.number", {1, 6, 10, 3, 0, 0, 0}, 4},
    {"satellite.variable.float.binary", {1, 6, 10, 4, 0, 0, 0}, 4},
    {"satellite.variable.float.hex", {1, 6, 10, 5, 0, 0, 0}, 4},
    {"satellite.variable.hex", {1, 6, 11, 0, 0, 0, 0}, 3},
    {"satellite.variable.hex()", {1, 6, 11, 0, 0, 0, 0}, 4},
    {"satellite.variable.hex.to_number", {1, 6, 11, 1, 0, 0, 0}, 4},
    {"satellite.variable.hex.width", {1, 6, 11, 2, 0, 0, 0}, 4},
    {"satellite.variable.hex.to_string", {1, 6, 11, 3, 0, 0, 0}, 4},
    {"satellite.variable.hex.digits", {1, 6, 11, 4, 0, 0, 0}, 4},
    {"satellite.variable.hex.to_binary", {1, 6, 11, 5, 0, 0, 0}, 4},
    {"satellite.variable.hex(x)", {1, 6, 11, 6, 0, 0, 0}, 4},
    {"satellite.variable.hex.string", {1, 6, 11, 7, 0, 0, 0}, 4},
    {"satellite.variable.hex.number", {1, 6, 11, 8, 0, 0, 0}, 4},
    {"satellite.variable.hex.binary", {1, 6, 11, 9, 0, 0, 0}, 4},
    {"satellite.variable.hex.hex", {1, 6, 11, 10, 0, 0, 0}, 4},
    {"satellite.variable.network", {1, 6, 12, 0, 0, 0, 0}, 3},
    {"satellite.variable.thread", {1, 6, 13, 0, 0, 0, 0}, 3},
    {"satellite.variable.thread()", {1, 6, 13, 0, 0, 0, 0}, 4},
    {"satellite.variable.thread.start()", {1, 6, 13, 1, 0, 0, 0}, 4},
    {"satellite.variable.thread.join()", {1, 6, 13, 2, 0, 0, 0}, 4},
    {"satellite.variable.variant", {1, 6, 14, 0, 0, 0, 0}, 3},
    {"satellite.variable.variant()", {1, 6, 14, 0, 0, 0, 0}, 4},
    {"satellite.variable.variant.holding", {1, 6, 14, 1, 0, 0, 0}, 4},
    {"satellite.variable.variant.holds(x)", {1, 6, 14, 2, 0, 0, 0}, 4},
    {"satellite.variable.variant.held", {1, 6, 14, 3, 0, 0, 0}, 4},
    {"satellite.variable.variant.clear", {1, 6, 14, 4, 0, 0, 0}, 4},
    {"satellite.variable.capsule", {1, 6, 15, 0, 0, 0, 0}, 3},
    {"satellite.random", {1, 7, 0, 0, 0, 0, 0}, 2},
    {"satellite.random()", {1, 7, 0, 0, 0, 0, 0}, 3},
    {"satellite.random.fast()", {1, 7, 1, 0, 0, 0, 0}, 3},
    {"satellite.random.normal()", {1, 7, 2, 0, 0, 0, 0}, 3},
    {"satellite.random.ultra()", {1, 7, 3, 0, 0, 0, 0}, 3},
    {"satellite.random.fast(digits)", {1, 7, 4, 0, 0, 0, 0}, 3},
    {"satellite.random.fast(min, max)", {1, 7, 5, 0, 0, 0, 0}, 3},
    {"satellite.random.fast(min, max, step)", {1, 7, 6, 0, 0, 0, 0}, 3},
    {"satellite.random.normal(digits)", {1, 7, 7, 0, 0, 0, 0}, 3},
    {"satellite.random.normal(min, max)", {1, 7, 8, 0, 0, 0, 0}, 3},
    {"satellite.random.normal(min, max, step)", {1, 7, 9, 0, 0, 0, 0}, 3},
    {"satellite.random.ultra(digits)", {1, 7, 10, 0, 0, 0, 0}, 3},
    {"satellite.random.ultra(min, max)", {1, 7, 11, 0, 0, 0, 0}, 3},
    {"satellite.random.ultra(min, max, step)", {1, 7, 12, 0, 0, 0, 0}, 3},
    {"satellite.random.seeded(seed)", {1, 7, 13, 0, 0, 0, 0}, 3},
    {"satellite.random.seeded(min, max)", {1, 7, 14, 0, 0, 0, 0}, 3},
    {"satellite.random.seeded(min, max, step)", {1, 7, 15, 0, 0, 0, 0}, 3},
    {"satellite.random.seeded()", {1, 7, 16, 0, 0, 0, 0}, 3},
    {"satellite.file", {1, 8, 0, 0, 0, 0, 0}, 2},
    {"satellite.file()", {1, 8, 0, 0, 0, 0, 0}, 3},
    {"satellite.file.new(path)", {1, 8, 1, 0, 0, 0, 0}, 3},
    {"satellite.file.open(path, mode)", {1, 8, 2, 0, 0, 0, 0}, 3},
    {"satellite.file.clear(path)", {1, 8, 3, 0, 0, 0, 0}, 3},
    {"satellite.file.new(path, mode)", {1, 8, 4, 0, 0, 0, 0}, 3},
    {"satellite.file.exists(path)", {1, 8, 5, 0, 0, 0, 0}, 3},
    {"satellite.time", {1, 9, 0, 0, 0, 0, 0}, 2},
    {"satellite.time()", {1, 9, 0, 0, 0, 0, 0}, 3},
    {"satellite.time.now", {1, 9, 1, 0, 0, 0, 0}, 3},
    {"satellite.time.new", {1, 9, 2, 0, 0, 0, 0}, 3},
    {"satellite.time.sleep(n)", {1, 9, 3, 0, 0, 0, 0}, 3},
    {"satellite.time.sleep(n, unit)", {1, 9, 4, 0, 0, 0, 0}, 3},
    {"satellite.spacesuit", {1, 10, 0, 0, 0, 0, 0}, 2},
    {"satellite.spacesuit()", {1, 10, 0, 0, 0, 0, 0}, 3},
    {"satellite.protected", {1, 11, 0, 0, 0, 0, 0}, 2},
    {"satellite.protected()", {1, 11, 0, 0, 0, 0, 0}, 3},
    {"satellite.public", {1, 12, 0, 0, 0, 0, 0}, 2},
    {"satellite.public()", {1, 12, 0, 0, 0, 0, 0}, 3},
    {"satellite.statement", {1, 13, 0, 0, 0, 0, 0}, 2},
    {"satellite.statement()", {1, 13, 0, 0, 0, 0, 0}, 3},
    {"satellite.statement.if", {1, 13, 1, 0, 0, 0, 0}, 3},
    {"satellite.statement.for", {1, 13, 2, 0, 0, 0, 0}, 3},
    {"satellite.statement.while", {1, 13, 3, 0, 0, 0, 0}, 3},
    {"satellite.statement.else", {1, 13, 4, 0, 0, 0, 0}, 3},
    {"satellite.library", {1, 14, 0, 0, 0, 0, 0}, 2},
    {"satellite.library()", {1, 14, 0, 0, 0, 0, 0}, 3},
    {"satellite.library.main", {1, 14, 1, 0, 0, 0, 0}, 3},
    {"satellite.library.main()", {1, 14, 1, 0, 0, 0, 0}, 4},
    {"satellite.library.main.arguments", {1, 14, 1, 1, 0, 0, 0}, 4},
    {"satellite.library.main.arguments()", {1, 14, 1, 1, 0, 0, 0}, 5},
    {"satellite.library.main.arguments.machine", {1, 14, 1, 1, 1, 0, 0}, 5},
    {"satellite.library.main.arguments.machine()", {1, 14, 1, 1, 1, 0, 0}, 6},
    {"satellite.library.main.arguments.machine.cores", {1, 14, 1, 1, 1, 1, 0}, 6},
    {"satellite.library.main.arguments.machine.cpu", {1, 14, 1, 1, 1, 2, 0}, 6},
    {"satellite.library.main.arguments.machine.threads", {1, 14, 1, 1, 1, 3, 0}, 6},
    {"satellite.library.main.arguments.machine.architecture", {1, 14, 1, 1, 1, 4, 0}, 6},
    {"satellite.library.main.arguments.machine.byte_order", {1, 14, 1, 1, 1, 5, 0}, 6},
    {"satellite.library.main.arguments.machine.page_size", {1, 14, 1, 1, 1, 6, 0}, 6},
    {"satellite.library.main.arguments.machine.pointer_bits", {1, 14, 1, 1, 1, 7, 0}, 6},
    {"satellite.library.main.arguments.memory", {1, 14, 1, 1, 2, 0, 0}, 5},
    {"satellite.library.main.arguments.memory()", {1, 14, 1, 1, 2, 0, 0}, 6},
    {"satellite.library.main.arguments.memory.total", {1, 14, 1, 1, 2, 1, 0}, 6},
    {"satellite.library.main.arguments.username", {1, 14, 1, 1, 3, 0, 0}, 5},
    {"satellite.library.main.arguments.system", {1, 14, 1, 1, 4, 0, 0}, 5},
    {"satellite.library.main.arguments.system()", {1, 14, 1, 1, 4, 0, 0}, 6},
    {"satellite.library.main.arguments.system.name", {1, 14, 1, 1, 4, 1, 0}, 6},
    {"satellite.library.main.arguments.system.kernel", {1, 14, 1, 1, 4, 2, 0}, 6},
    {"satellite.library.main.arguments.system.kernel_version", {1, 14, 1, 1, 4, 3, 0}, 6},
    {"satellite.library.main.arguments.system.distribution", {1, 14, 1, 1, 4, 4, 0}, 6},
    {"satellite.library.main.arguments.system.distribution_id", {1, 14, 1, 1, 4, 5, 0}, 6},
    {"satellite.library.main.arguments.system.distribution_version", {1, 14, 1, 1, 4, 6, 0}, 6},
    {"satellite.library.main.arguments.system.hostname", {1, 14, 1, 1, 4, 7, 0}, 6},
    {"satellite.library.main.arguments.build", {1, 14, 1, 1, 5, 0, 0}, 5},
    {"satellite.library.main.arguments.build()", {1, 14, 1, 1, 5, 0, 0}, 6},
    {"satellite.library.main.arguments.build.compiler", {1, 14, 1, 1, 5, 1, 0}, 6},
    {"satellite.library.main.arguments.build.compiler_version", {1, 14, 1, 1, 5, 2, 0}, 6},
    {"satellite.library.main.arguments.build.standard", {1, 14, 1, 1, 5, 3, 0}, 6},
    {"satellite.library.main.arguments.build.flags", {1, 14, 1, 1, 5, 4, 0}, 6},
    {"satellite.library.main.arguments.build.make", {1, 14, 1, 1, 5, 5, 0}, 6},
    {"satellite.library.main.arguments.build.standard_library", {1, 14, 1, 1, 5, 6, 0}, 6},
    {"satellite.library.main.arguments.build.c_library", {1, 14, 1, 1, 5, 7, 0}, 6},
    {"satellite.library.main.arguments.build.built", {1, 14, 1, 1, 5, 8, 0}, 6},
    {"satellite.library.main.arguments.interpreter", {1, 14, 1, 1, 6, 0, 0}, 5},
    {"satellite.library.main.arguments.interpreter()", {1, 14, 1, 1, 6, 0, 0}, 6},
    {"satellite.library.main.arguments.interpreter.version", {1, 14, 1, 1, 6, 1, 0}, 6},
    {"satellite.library.main.arguments.interpreter.library_path", {1, 14, 1, 1, 6, 2, 0}, 6},
    {"satellite.library.main.arguments.interpreter.library_path_source", {1, 14, 1, 1, 6, 3, 0}, 6},
    {"satellite.library.main.arguments.process", {1, 14, 1, 1, 7, 0, 0}, 5},
    {"satellite.library.main.arguments.process()", {1, 14, 1, 1, 7, 0, 0}, 6},
    {"satellite.library.main.arguments.process.id", {1, 14, 1, 1, 7, 1, 0}, 6},
    {"satellite.library.main.arguments.process.parent", {1, 14, 1, 1, 7, 2, 0}, 6},
    {"satellite.library.main.arguments.session", {1, 14, 1, 1, 8, 0, 0}, 5},
    {"satellite.library.main.arguments.session()", {1, 14, 1, 1, 8, 0, 0}, 6},
    {"satellite.library.main.arguments.session.shell", {1, 14, 1, 1, 8, 1, 0}, 6},
    {"satellite.library.main.arguments.session.terminal", {1, 14, 1, 1, 8, 2, 0}, 6},
    {"satellite.library.main.arguments.session.language", {1, 14, 1, 1, 8, 3, 0}, 6},
    {"satellite.library.main.arguments.session.home", {1, 14, 1, 1, 8, 4, 0}, 6},
    {"satellite.library.main.arguments.session.directory", {1, 14, 1, 1, 8, 5, 0}, 6},
    {"satellite.library.main.arguments.length", {1, 14, 1, 1, 9, 0, 0}, 5},
    {"satellite.library.system", {1, 14, 2, 0, 0, 0, 0}, 3},
    {"satellite.library.system()", {1, 14, 2, 0, 0, 0, 0}, 4},
    {"satellite.library.system.division_digits", {1, 14, 2, 1, 0, 0, 0}, 4},
    {"satellite.library.system.max_depth", {1, 14, 2, 2, 0, 0, 0}, 4},
    {"satellite.library.system.min_free_mb", {1, 14, 2, 3, 0, 0, 0}, 4},
    {"satellite.library.system.float_digits", {1, 14, 2, 4, 0, 0, 0}, 4},
    {"satellite.return", {1, 15, 0, 0, 0, 0, 0}, 2},
    {"satellite.return()", {1, 15, 0, 0, 0, 0, 0}, 3},
    {"satellite.return(satellite)", {1, 15, 1, 0, 0, 0, 0}, 3},
    {"satellite.return(value)", {1, 15, 2, 0, 0, 0, 0}, 3},
    {"satellite.analyze", {1, 16, 0, 0, 0, 0, 0}, 2},
    {"satellite.bool", {1, 17, 0, 0, 0, 0, 0}, 2},
    {"satellite.bool()", {1, 17, 0, 0, 0, 0, 0}, 3},
    {"satellite.bool.false", {1, 17, 1, 0, 0, 0, 0}, 3},
    {"satellite.bool.true", {1, 17, 2, 0, 0, 0, 0}, 3},
    {"satellite.directory", {1, 18, 0, 0, 0, 0, 0}, 2},
    {"satellite.directory()", {1, 18, 0, 0, 0, 0, 0}, 3},
    {"satellite.directory.change(d)", {1, 18, 1, 0, 0, 0, 0}, 3},
    {"satellite.directory.current()", {1, 18, 2, 0, 0, 0, 0}, 3},
    {"satellite.directory.exists(d)", {1, 18, 3, 0, 0, 0, 0}, 3},
    {"satellite.directory.list()", {1, 18, 4, 0, 0, 0, 0}, 3},
    {"satellite.directory.list(d)", {1, 18, 5, 0, 0, 0, 0}, 3},
    {"satellite.help", {1, 19, 0, 0, 0, 0, 0}, 2},
    {"satellite.help()", {1, 19, 0, 0, 0, 0, 0}, 3},
    {"satellite.help(x)", {1, 19, 1, 0, 0, 0, 0}, 3},
    {"satellite.network", {1, 20, 0, 0, 0, 0, 0}, 2},
    {"satellite.network()", {1, 20, 0, 0, 0, 0, 0}, 3},
    {"satellite.network.http(port)", {1, 20, 1, 0, 0, 0, 0}, 3},
    {"satellite.network.https(host, port)", {1, 20, 2, 0, 0, 0, 0}, 3},
    {"satellite.network.new", {1, 20, 3, 0, 0, 0, 0}, 3},
    {"satellite.network.open", {1, 20, 4, 0, 0, 0, 0}, 3},
    {"satellite.network.receive", {1, 20, 5, 0, 0, 0, 0}, 3},
    {"satellite.network.http(host, port)", {1, 20, 6, 0, 0, 0, 0}, 3},
    {"satellite.network.https(port, cert, key)", {1, 20, 7, 0, 0, 0, 0}, 3},
    {"satellite.returns", {1, 21, 0, 0, 0, 0, 0}, 2},
    {"satellite.system", {1, 22, 0, 0, 0, 0, 0}, 2},
    {"satellite.system()", {1, 22, 0, 0, 0, 0, 0}, 3},
    {"satellite.system.delete(x)", {1, 22, 1, 0, 0, 0, 0}, 3},
    {"satellite.system.environment", {1, 22, 2, 0, 0, 0, 0}, 3},
    {"satellite.system.home", {1, 22, 3, 0, 0, 0, 0}, 3},
    {"satellite.system.memory", {1, 22, 4, 0, 0, 0, 0}, 3},
    {"satellite.system.memory()", {1, 22, 4, 0, 0, 0, 0}, 4},
    {"satellite.system.memory.bit", {1, 22, 4, 1, 0, 0, 0}, 4},
    {"satellite.system.memory.frequency", {1, 22, 4, 2, 0, 0, 0}, 4},
    {"satellite.system.memory.main()", {1, 22, 4, 3, 0, 0, 0}, 4},
    {"satellite.system.memory.swap", {1, 22, 4, 4, 0, 0, 0}, 4},
    {"satellite.system.memory.swap()", {1, 22, 4, 4, 0, 0, 0}, 5},
    {"satellite.system.memory.swap.free()", {1, 22, 4, 4, 1, 0, 0}, 5},
    {"satellite.system.memory.swap.total()", {1, 22, 4, 4, 2, 0, 0}, 5},
    {"satellite.system.memory.swap.used", {1, 22, 4, 4, 3, 0, 0}, 5},
    {"satellite.system.memory.swap.free(unit)", {1, 22, 4, 4, 4, 0, 0}, 5},
    {"satellite.system.memory.swap.total(unit)", {1, 22, 4, 4, 5, 0, 0}, 5},
    {"satellite.system.memory.swap(unit)", {1, 22, 4, 4, 6, 0, 0}, 5},
    {"satellite.system.memory.swap.used(unit)", {1, 22, 4, 4, 7, 0, 0}, 5},
    {"satellite.system.memory.this", {1, 22, 4, 5, 0, 0, 0}, 4},
    {"satellite.system.memory.this()", {1, 22, 4, 5, 0, 0, 0}, 5},
    {"satellite.system.memory.this.available()", {1, 22, 4, 5, 1, 0, 0}, 5},
    {"satellite.system.memory.this.free()", {1, 22, 4, 5, 2, 0, 0}, 5},
    {"satellite.system.memory.this.used", {1, 22, 4, 5, 3, 0, 0}, 5},
    {"satellite.system.memory.this.available(unit)", {1, 22, 4, 5, 4, 0, 0}, 5},
    {"satellite.system.memory.this.free(unit)", {1, 22, 4, 5, 5, 0, 0}, 5},
    {"satellite.system.memory.this.used(unit)", {1, 22, 4, 5, 6, 0, 0}, 5},
    {"satellite.system.memory.free()", {1, 22, 4, 6, 0, 0, 0}, 4},
    {"satellite.system.memory.total()", {1, 22, 4, 7, 0, 0, 0}, 4},
    {"satellite.system.memory.used()", {1, 22, 4, 8, 0, 0, 0}, 4},
    {"satellite.system.memory.main(unit)", {1, 22, 4, 9, 0, 0, 0}, 4},
    {"satellite.system.memory.free(unit)", {1, 22, 4, 10, 0, 0, 0}, 4},
    {"satellite.system.memory.total(unit)", {1, 22, 4, 11, 0, 0, 0}, 4},
    {"satellite.system.memory.used(unit)", {1, 22, 4, 12, 0, 0, 0}, 4},
    {"satellite.system.threshold()", {1, 22, 5, 0, 0, 0, 0}, 3},
    {"satellite.system.threshold(n)", {1, 22, 6, 0, 0, 0, 0}, 3},
    {"satellite.system.persist()", {1, 22, 7, 0, 0, 0, 0}, 3},
    {"satellite.system.persist(x)", {1, 22, 8, 0, 0, 0, 0}, 3},
    {"satellite.system.environment(name)", {1, 22, 9, 0, 0, 0, 0}, 3},
    {"satellite.thread", {1, 23, 0, 0, 0, 0, 0}, 2},
    {"satellite.thread()", {1, 23, 0, 0, 0, 0, 0}, 3},
    {"satellite.thread.new", {1, 23, 1, 0, 0, 0, 0}, 3},
    {"satellite.constructor", {1, 24, 0, 0, 0, 0, 0}, 2},
    {"satellite.constructor()", {1, 24, 0, 0, 0, 0, 0}, 3},
    {"satellite.variable.percentage", {1, 6, 16, 0, 0, 0, 0}, 3},
    {"satellite.library.main.arguments.access", {1, 14, 1, 1, 10, 0, 0}, 5},
    {"satellite.library.main.arguments.history", {1, 14, 1, 1, 11, 0, 0}, 5},
    {"satellite.file.open(path)", {1, 8, 6, 0, 0, 0, 0}, 3},
    {"satellite.library.main.arguments.memory.free", {1, 14, 1, 1, 2, 2, 0}, 6},
    {"satellite.library.main.arguments.memory.used", {1, 14, 1, 1, 2, 3, 0}, 6},
    {"satellite.library.main.arguments.directory", {1, 14, 1, 1, 12, 0, 0}, 5},
    {"satellite.library.main.arguments.cores", {1, 14, 1, 1, 13, 0, 0}, 5},
    {"satellite.library.main.arguments.threads", {1, 14, 1, 1, 14, 0, 0}, 5},
    {"satellite.library.main.arguments.user", {1, 14, 1, 1, 15, 0, 0}, 5},
    {"satellite.library.main.arguments.ram", {1, 14, 1, 1, 16, 0, 0}, 5},
    {"satellite.library.main.arguments.dir", {1, 14, 1, 1, 17, 0, 0}, 5},
    {"satellite.feedback", {1, 25, 0, 0, 0, 0, 0}, 2},
    {"satellite.feedback()", {1, 25, 0, 0, 0, 0, 0}, 3},
    {"satellite.feedback(x)", {1, 25, 1, 0, 0, 0, 0}, 3},
    {"satellite.container.index", {1, 4, 5, 0, 0, 0, 0}, 3},
    {"satellite.container.multiple", {1, 4, 6, 0, 0, 0, 0}, 3},
    {"satellite.variable.infinity", {1, 6, 17, 0, 0, 0, 0}, 3},
    {"satellite.infinity", {1, 26, 0, 0, 0, 0, 0}, 2},
    {"satellite.infinity()", {1, 26, 0, 0, 0, 0, 0}, 3},
    {"satellite.variable.window", {1, 6, 18, 0, 0, 0, 0}, 3},
    {"satellite.window", {1, 27, 0, 0, 0, 0, 0}, 2},
    {"satellite.window.new(title, width, height)", {1, 27, 1, 0, 0, 0, 0}, 3},
    {"satellite.window.button(text)", {1, 27, 2, 0, 0, 0, 0}, 3},
    {"satellite.window.label(text)", {1, 27, 3, 0, 0, 0, 0}, 3},
    {"satellite.window.text_box(text)", {1, 27, 4, 0, 0, 0, 0}, 3},
    {"satellite.window.text_area(text)", {1, 27, 5, 0, 0, 0, 0}, 3},
    {"satellite.window.checkbox(text)", {1, 27, 6, 0, 0, 0, 0}, 3},
    {"satellite.window.switch", {1, 27, 7, 0, 0, 0, 0}, 3},
    {"satellite.window.switch()", {1, 27, 7, 0, 0, 0, 0}, 4},
    {"satellite.window.slider(least, most)", {1, 27, 8, 0, 0, 0, 0}, 3},
    {"satellite.window.number_box(least, most)", {1, 27, 9, 0, 0, 0, 0}, 3},
    {"satellite.window.progress", {1, 27, 10, 0, 0, 0, 0}, 3},
    {"satellite.window.progress()", {1, 27, 10, 0, 0, 0, 0}, 4},
    {"satellite.window.choice(items)", {1, 27, 11, 0, 0, 0, 0}, 3},
    {"satellite.window.row", {1, 27, 12, 0, 0, 0, 0}, 3},
    {"satellite.window.row()", {1, 27, 12, 0, 0, 0, 0}, 4},
    {"satellite.window.column", {1, 27, 13, 0, 0, 0, 0}, 3},
    {"satellite.window.column()", {1, 27, 13, 0, 0, 0, 0}, 4},
    {"satellite.window.grid", {1, 27, 14, 0, 0, 0, 0}, 3},
    {"satellite.window.grid()", {1, 27, 14, 0, 0, 0, 0}, 4},
    {"satellite.window.picture(path)", {1, 27, 15, 0, 0, 0, 0}, 3},
    {"satellite.window.scroll", {1, 27, 16, 0, 0, 0, 0}, 3},
    {"satellite.window.scroll()", {1, 27, 16, 0, 0, 0, 0}, 4},
    {"satellite.window.frame(title)", {1, 27, 17, 0, 0, 0, 0}, 3},
    {"satellite.window.split", {1, 27, 18, 0, 0, 0, 0}, 3},
    {"satellite.window.split()", {1, 27, 18, 0, 0, 0, 0}, 4},
    {"satellite.window.menu(title)", {1, 27, 19, 0, 0, 0, 0}, 3},
    {"satellite.window.canvas(width, height)", {1, 27, 20, 0, 0, 0, 0}, 3},
    {"satellite.window.tabs", {1, 27, 21, 0, 0, 0, 0}, 3},
    {"satellite.window.tabs()", {1, 27, 21, 0, 0, 0, 0}, 4},
    {"satellite.window.one_of(items)", {1, 27, 22, 0, 0, 0, 0}, 3},
    {"satellite.console.new(title, width, height)", {1, 5, 10, 0, 0, 0, 0}, 3},
    {"satellite.namespace", {1, 28, 0, 0, 0, 0, 0}, 2},
    {"satellite.variable.color", {1, 6, 19, 0, 0, 0, 0}, 3},
    {"satellite.variable.fraction", {1, 6, 20, 0, 0, 0, 0}, 3},
    {"satellite.variable.arguments", {1, 6, 21, 0, 0, 0, 0}, 3},
};

inline constexpr std::size_t kWordFactsCount = sizeof kWordFacts / sizeof kWordFacts[0];

// The same words sorted by SPELLING, so the lexer can turn the text
// satellite.console.display into one code without walking 364 rows --
// and words/aliases.tsv's second spellings among them, each with its
// word's code, so satellite.space lexes as satellite.namespace.
struct SpelledWord { const char *path; token::Code code; };

inline constexpr SpelledWord kSpelledWords[] = {
    {"satellite", 4097},
    {"satellite.analyze", 4392},
    {"satellite.bool", 4393},
    {"satellite.bool()", 4394},
    {"satellite.bool.false", 4395},
    {"satellite.bool.true", 4396},
    {"satellite.capsule", 4102},
    {"satellite.capsule()", 4103},
    {"satellite.capsule.launch", 4104},
    {"satellite.class", 4315},
    {"satellite.console", 4161},
    {"satellite.console()", 4162},
    {"satellite.console.clear()", 4170},
    {"satellite.console.display", 4163},
    {"satellite.console.height", 4169},
    {"satellite.console.home()", 4171},
    {"satellite.console.input()", 4164},
    {"satellite.console.input(prompt)", 4165},
    {"satellite.console.input(prompt, target)", 4166},
    {"satellite.console.new(title, width, height)", 4513},
    {"satellite.console.typed()", 4167},
    {"satellite.console.width", 4168},
    {"satellite.constructor", 4459},
    {"satellite.constructor()", 4460},
    {"satellite.container", 4107},
    {"satellite.container()", 4108},
    {"satellite.container.arguments", 4149},
    {"satellite.container.arguments.contains(x)", 4159},
    {"satellite.container.arguments.count", 4151},
    {"satellite.container.arguments.first", 4157},
    {"satellite.container.arguments.get(k)", 4156},
    {"satellite.container.arguments.has(k)", 4155},
    {"satellite.container.arguments.keys", 4152},
    {"satellite.container.arguments.last", 4158},
    {"satellite.container.arguments.length", 4150},
    {"satellite.container.arguments.lines", 4154},
    {"satellite.container.arguments.to_string", 4153},
    {"satellite.container.index", 4476},
    {"satellite.container.list", 4121},
    {"satellite.container.list()", 4122},
    {"satellite.container.list.append", 4123},
    {"satellite.container.list.clear", 4133},
    {"satellite.container.list.contains(x)", 4130},
    {"satellite.container.list.empty", 4132},
    {"satellite.container.list.first", 4134},
    {"satellite.container.list.index_of(x)", 4131},
    {"satellite.container.list.insert(n, x)", 4142},
    {"satellite.container.list.join(separator)", 4143},
    {"satellite.container.list.last", 4135},
    {"satellite.container.list.max", 4146},
    {"satellite.container.list.min", 4147},
    {"satellite.container.list.remove(x)", 4141},
    {"satellite.container.list.remove_at(n)", 4140},
    {"satellite.container.list.remove_first()", 4138},
    {"satellite.container.list.remove_last()", 4139},
    {"satellite.container.list.reserve(n)", 4137},
    {"satellite.container.list.reverse", 4144},
    {"satellite.container.list.search(pattern)", 4148},
    {"satellite.container.list.size", 4124},
    {"satellite.container.list.sort()", 4125},
    {"satellite.container.list.sort(direction)", 4126},
    {"satellite.container.list.sort_down()", 4127},
    {"satellite.container.list.sort_down(key)", 4128},
    {"satellite.container.list.sort_up(key)", 4129},
    {"satellite.container.list.sum", 4145},
    {"satellite.container.list.truncate(n)", 4136},
    {"satellite.container.map", 4109},
    {"satellite.container.map()", 4110},
    {"satellite.container.map.clear", 4116},
    {"satellite.container.map.empty", 4115},
    {"satellite.container.map.get(k)", 4112},
    {"satellite.container.map.has(k)", 4113},
    {"satellite.container.map.keys", 4118},
    {"satellite.container.map.remove(k)", 4117},
    {"satellite.container.map.search(pattern)", 4120},
    {"satellite.container.map.set(k, v)", 4111},
    {"satellite.container.map.size", 4114},
    {"satellite.container.map.values", 4119},
    {"satellite.container.multiple", 4477},
    {"satellite.container.result", 4160},
    {"satellite.directory", 4397},
    {"satellite.directory()", 4398},
    {"satellite.directory.change(d)", 4399},
    {"satellite.directory.current()", 4400},
    {"satellite.directory.exists(d)", 4401},
    {"satellite.directory.list()", 4402},
    {"satellite.directory.list(d)", 4403},
    {"satellite.feedback", 4473},
    {"satellite.feedback()", 4474},
    {"satellite.feedback(x)", 4475},
    {"satellite.file", 4302},
    {"satellite.file()", 4303},
    {"satellite.file.clear(path)", 4306},
    {"satellite.file.exists(path)", 4308},
    {"satellite.file.new(path)", 4304},
    {"satellite.file.new(path, mode)", 4307},
    {"satellite.file.open(path)", 4464},
    {"satellite.file.open(path, mode)", 4305},
    {"satellite.help", 4404},
    {"satellite.help()", 4405},
    {"satellite.help(x)", 4406},
    {"satellite.include", 4098},
    {"satellite.include()", 4099},
    {"satellite.include(satellite)", 4100},
    {"satellite.include(spaceship)", 4101},
    {"satellite.infinity", 4479},
    {"satellite.infinity()", 4480},
    {"satellite.library", 4327},
    {"satellite.library()", 4328},
    {"satellite.library.main", 4329},
    {"satellite.library.main()", 4330},
    {"satellite.library.main.arguments", 4331},
    {"satellite.library.main.arguments()", 4332},
    {"satellite.library.main.arguments.access", 4462},
    {"satellite.library.main.arguments.build", 4355},
    {"satellite.library.main.arguments.build()", 4356},
    {"satellite.library.main.arguments.build.built", 4364},
    {"satellite.library.main.arguments.build.c_library", 4363},
    {"satellite.library.main.arguments.build.compiler", 4357},
    {"satellite.library.main.arguments.build.compiler_version", 4358},
    {"satellite.library.main.arguments.build.flags", 4360},
    {"satellite.library.main.arguments.build.make", 4361},
    {"satellite.library.main.arguments.build.standard", 4359},
    {"satellite.library.main.arguments.build.standard_library", 4362},
    {"satellite.library.main.arguments.cores", 4468},
    {"satellite.library.main.arguments.dir", 4472},
    {"satellite.library.main.arguments.directory", 4467},
    {"satellite.library.main.arguments.history", 4463},
    {"satellite.library.main.arguments.interpreter", 4365},
    {"satellite.library.main.arguments.interpreter()", 4366},
    {"satellite.library.main.arguments.interpreter.library_path", 4368},
    {"satellite.library.main.arguments.interpreter.library_path_source", 4369},
    {"satellite.library.main.arguments.interpreter.version", 4367},
    {"satellite.library.main.arguments.length", 4381},
    {"satellite.library.main.arguments.machine", 4333},
    {"satellite.library.main.arguments.machine()", 4334},
    {"satellite.library.main.arguments.machine.architecture", 4338},
    {"satellite.library.main.arguments.machine.byte_order", 4339},
    {"satellite.library.main.arguments.machine.cores", 4335},
    {"satellite.library.main.arguments.machine.cpu", 4336},
    {"satellite.library.main.arguments.machine.page_size", 4340},
    {"satellite.library.main.arguments.machine.pointer_bits", 4341},
    {"satellite.library.main.arguments.machine.threads", 4337},
    {"satellite.library.main.arguments.memory", 4342},
    {"satellite.library.main.arguments.memory()", 4343},
    {"satellite.library.main.arguments.memory.free", 4465},
    {"satellite.library.main.arguments.memory.total", 4344},
    {"satellite.library.main.arguments.memory.used", 4466},
    {"satellite.library.main.arguments.process", 4370},
    {"satellite.library.main.arguments.process()", 4371},
    {"satellite.library.main.arguments.process.id", 4372},
    {"satellite.library.main.arguments.process.parent", 4373},
    {"satellite.library.main.arguments.ram", 4471},
    {"satellite.library.main.arguments.session", 4374},
    {"satellite.library.main.arguments.session()", 4375},
    {"satellite.library.main.arguments.session.directory", 4380},
    {"satellite.library.main.arguments.session.home", 4379},
    {"satellite.library.main.arguments.session.language", 4378},
    {"satellite.library.main.arguments.session.shell", 4376},
    {"satellite.library.main.arguments.session.terminal", 4377},
    {"satellite.library.main.arguments.system", 4346},
    {"satellite.library.main.arguments.system()", 4347},
    {"satellite.library.main.arguments.system.distribution", 4351},
    {"satellite.library.main.arguments.system.distribution_id", 4352},
    {"satellite.library.main.arguments.system.distribution_version", 4353},
    {"satellite.library.main.arguments.system.hostname", 4354},
    {"satellite.library.main.arguments.system.kernel", 4349},
    {"satellite.library.main.arguments.system.kernel_version", 4350},
    {"satellite.library.main.arguments.system.name", 4348},
    {"satellite.library.main.arguments.threads", 4469},
    {"satellite.library.main.arguments.user", 4470},
    {"satellite.library.main.arguments.username", 4345},
    {"satellite.library.system", 4382},
    {"satellite.library.system()", 4383},
    {"satellite.library.system.division_digits", 4384},
    {"satellite.library.system.float_digits", 4387},
    {"satellite.library.system.max_depth", 4385},
    {"satellite.library.system.min_free_mb", 4386},
    {"satellite.main", 4105},
    {"satellite.main()", 4106},
    {"satellite.namespace", 4514},
    {"satellite.network", 4407},
    {"satellite.network()", 4408},
    {"satellite.network.http(host, port)", 4414},
    {"satellite.network.http(port)", 4409},
    {"satellite.network.https(host, port)", 4410},
    {"satellite.network.https(port, cert, key)", 4415},
    {"satellite.network.new", 4411},
    {"satellite.network.open", 4412},
    {"satellite.network.receive", 4413},
    {"satellite.protected", 4317},
    {"satellite.protected()", 4318},
    {"satellite.public", 4319},
    {"satellite.public()", 4320},
    {"satellite.random", 4284},
    {"satellite.random()", 4285},
    {"satellite.random.fast()", 4286},
    {"satellite.random.fast(digits)", 4289},
    {"satellite.random.fast(min, max)", 4290},
    {"satellite.random.fast(min, max, step)", 4291},
    {"satellite.random.normal()", 4287},
    {"satellite.random.normal(digits)", 4292},
    {"satellite.random.normal(min, max)", 4293},
    {"satellite.random.normal(min, max, step)", 4294},
    {"satellite.random.seeded()", 4301},
    {"satellite.random.seeded(min, max)", 4299},
    {"satellite.random.seeded(min, max, step)", 4300},
    {"satellite.random.seeded(seed)", 4298},
    {"satellite.random.ultra()", 4288},
    {"satellite.random.ultra(digits)", 4295},
    {"satellite.random.ultra(min, max)", 4296},
    {"satellite.random.ultra(min, max, step)", 4297},
    {"satellite.return", 4388},
    {"satellite.return()", 4389},
    {"satellite.return(satellite)", 4390},
    {"satellite.return(value)", 4391},
    {"satellite.returns", 4416},
    {"satellite.space", 4514},
    {"satellite.spacesuit", 4315},
    {"satellite.spacesuit()", 4316},
    {"satellite.statement", 4321},
    {"satellite.statement()", 4322},
    {"satellite.statement.else", 4326},
    {"satellite.statement.for", 4324},
    {"satellite.statement.if", 4323},
    {"satellite.statement.while", 4325},
    {"satellite.system", 4417},
    {"satellite.system()", 4418},
    {"satellite.system.delete(x)", 4419},
    {"satellite.system.environment", 4420},
    {"satellite.system.environment(name)", 4455},
    {"satellite.system.home", 4421},
    {"satellite.system.memory", 4422},
    {"satellite.system.memory()", 4423},
    {"satellite.system.memory.bit", 4424},
    {"satellite.system.memory.free()", 4444},
    {"satellite.system.memory.free(unit)", 4448},
    {"satellite.system.memory.frequency", 4425},
    {"satellite.system.memory.main()", 4426},
    {"satellite.system.memory.main(unit)", 4447},
    {"satellite.system.memory.swap", 4427},
    {"satellite.system.memory.swap()", 4428},
    {"satellite.system.memory.swap(unit)", 4434},
    {"satellite.system.memory.swap.free()", 4429},
    {"satellite.system.memory.swap.free(unit)", 4432},
    {"satellite.system.memory.swap.total()", 4430},
    {"satellite.system.memory.swap.total(unit)", 4433},
    {"satellite.system.memory.swap.used", 4431},
    {"satellite.system.memory.swap.used(unit)", 4435},
    {"satellite.system.memory.this", 4436},
    {"satellite.system.memory.this()", 4437},
    {"satellite.system.memory.this.available()", 4438},
    {"satellite.system.memory.this.available(unit)", 4441},
    {"satellite.system.memory.this.free()", 4439},
    {"satellite.system.memory.this.free(unit)", 4442},
    {"satellite.system.memory.this.used", 4440},
    {"satellite.system.memory.this.used(unit)", 4443},
    {"satellite.system.memory.total()", 4445},
    {"satellite.system.memory.total(unit)", 4449},
    {"satellite.system.memory.used()", 4446},
    {"satellite.system.memory.used(unit)", 4450},
    {"satellite.system.persist()", 4453},
    {"satellite.system.persist(x)", 4454},
    {"satellite.system.threshold()", 4451},
    {"satellite.system.threshold(n)", 4452},
    {"satellite.thread", 4456},
    {"satellite.thread()", 4457},
    {"satellite.thread.new", 4458},
    {"satellite.time", 4309},
    {"satellite.time()", 4310},
    {"satellite.time.new", 4312},
    {"satellite.time.now", 4311},
    {"satellite.time.sleep(n)", 4313},
    {"satellite.time.sleep(n, unit)", 4314},
    {"satellite.variable", 4172},
    {"satellite.variable()", 4173},
    {"satellite.variable.arguments", 4517},
    {"satellite.variable.bin", 4235},
    {"satellite.variable.binary", 4235},
    {"satellite.variable.binary()", 4236},
    {"satellite.variable.binary(x)", 4243},
    {"satellite.variable.binary.as_number", 4240},
    {"satellite.variable.binary.binary", 4246},
    {"satellite.variable.binary.clear", 4248},
    {"satellite.variable.binary.digits", 4241},
    {"satellite.variable.binary.hex", 4247},
    {"satellite.variable.binary.number", 4245},
    {"satellite.variable.binary.string", 4244},
    {"satellite.variable.binary.to_hex", 4242},
    {"satellite.variable.binary.to_number", 4237},
    {"satellite.variable.binary.to_string", 4239},
    {"satellite.variable.binary.width", 4238},
    {"satellite.variable.bool", 4249},
    {"satellite.variable.capsule", 4283},
    {"satellite.variable.color", 4515},
    {"satellite.variable.colour", 4515},
    {"satellite.variable.date", 4250},
    {"satellite.variable.double", 4253},
    {"satellite.variable.duration", 4251},
    {"satellite.variable.expression", 4252},
    {"satellite.variable.file", 4198},
    {"satellite.variable.file()", 4199},
    {"satellite.variable.file.close", 4205},
    {"satellite.variable.file.error", 4209},
    {"satellite.variable.file.exists", 4206},
    {"satellite.variable.file.new", 4200},
    {"satellite.variable.file.ok", 4207},
    {"satellite.variable.file.open", 4201},
    {"satellite.variable.file.path", 4208},
    {"satellite.variable.file.read_all", 4204},
    {"satellite.variable.file.read_line", 4202},
    {"satellite.variable.file.write(x)", 4210},
    {"satellite.variable.file.write_line(s)", 4203},
    {"satellite.variable.float", 4253},
    {"satellite.variable.float()", 4254},
    {"satellite.variable.float.binary", 4258},
    {"satellite.variable.float.hex", 4259},
    {"satellite.variable.float.number", 4257},
    {"satellite.variable.float.string", 4256},
    {"satellite.variable.float.to_string", 4255},
    {"satellite.variable.fraction", 4516},
    {"satellite.variable.hex", 4260},
    {"satellite.variable.hex()", 4261},
    {"satellite.variable.hex(x)", 4267},
    {"satellite.variable.hex.binary", 4270},
    {"satellite.variable.hex.digits", 4265},
    {"satellite.variable.hex.hex", 4271},
    {"satellite.variable.hex.number", 4269},
    {"satellite.variable.hex.string", 4268},
    {"satellite.variable.hex.to_binary", 4266},
    {"satellite.variable.hex.to_number", 4262},
    {"satellite.variable.hex.to_string", 4264},
    {"satellite.variable.hex.width", 4263},
    {"satellite.variable.hexadecimal", 4260},
    {"satellite.variable.infinity", 4478},
    {"satellite.variable.network", 4272},
    {"satellite.variable.number", 4213},
    {"satellite.variable.number()", 4214},
    {"satellite.variable.number(x)", 4230},
    {"satellite.variable.number.abs(a)", 4218},
    {"satellite.variable.number.binary", 4233},
    {"satellite.variable.number.ceil", 4222},
    {"satellite.variable.number.clamp(a, low, high)", 4219},
    {"satellite.variable.number.digits", 4229},
    {"satellite.variable.number.floor", 4221},
    {"satellite.variable.number.hex", 4234},
    {"satellite.variable.number.max(a, b)", 4216},
    {"satellite.variable.number.min(a, b)", 4217},
    {"satellite.variable.number.modulus(a, b)", 4226},
    {"satellite.variable.number.number", 4232},
    {"satellite.variable.number.power(a, b)", 4224},
    {"satellite.variable.number.round", 4223},
    {"satellite.variable.number.shift_left(n)", 4215},
    {"satellite.variable.number.shift_right(n)", 4225},
    {"satellite.variable.number.sqrt(a)", 4228},
    {"satellite.variable.number.string", 4231},
    {"satellite.variable.number.to_string", 4220},
    {"satellite.variable.number.truncate(a)", 4227},
    {"satellite.variable.percent", 4461},
    {"satellite.variable.percentage", 4461},
    {"satellite.variable.string", 4174},
    {"satellite.variable.string()", 4175},
    {"satellite.variable.string(x)", 4193},
    {"satellite.variable.string.append(x)", 4189},
    {"satellite.variable.string.at(n)", 4191},
    {"satellite.variable.string.binary", 4196},
    {"satellite.variable.string.clear", 4190},
    {"satellite.variable.string.contains(x)", 4179},
    {"satellite.variable.string.empty", 4177},
    {"satellite.variable.string.ends_with(x)", 4182},
    {"satellite.variable.string.find(x)", 4178},
    {"satellite.variable.string.hex", 4197},
    {"satellite.variable.string.lower", 4183},
    {"satellite.variable.string.number", 4195},
    {"satellite.variable.string.replace(a, b)", 4187},
    {"satellite.variable.string.resolved", 4192},
    {"satellite.variable.string.size", 4176},
    {"satellite.variable.string.split(separator)", 4185},
    {"satellite.variable.string.starts_with(x)", 4181},
    {"satellite.variable.string.string", 4194},
    {"satellite.variable.string.substring(start, end)", 4180},
    {"satellite.variable.string.to_number", 4188},
    {"satellite.variable.string.trim", 4186},
    {"satellite.variable.string.upper", 4184},
    {"satellite.variable.thread", 4273},
    {"satellite.variable.thread()", 4274},
    {"satellite.variable.thread.join()", 4276},
    {"satellite.variable.thread.start()", 4275},
    {"satellite.variable.time", 4211},
    {"satellite.variable.time()", 4212},
    {"satellite.variable.variant", 4277},
    {"satellite.variable.variant()", 4278},
    {"satellite.variable.variant.clear", 4282},
    {"satellite.variable.variant.held", 4281},
    {"satellite.variable.variant.holding", 4279},
    {"satellite.variable.variant.holds(x)", 4280},
    {"satellite.variable.window", 4481},
    {"satellite.window", 4482},
    {"satellite.window.button(text)", 4484},
    {"satellite.window.canvas(width, height)", 4509},
    {"satellite.window.checkbox(text)", 4488},
    {"satellite.window.choice(items)", 4495},
    {"satellite.window.column", 4498},
    {"satellite.window.column()", 4499},
    {"satellite.window.frame(title)", 4505},
    {"satellite.window.grid", 4500},
    {"satellite.window.grid()", 4501},
    {"satellite.window.label(text)", 4485},
    {"satellite.window.menu(title)", 4508},
    {"satellite.window.new(title, width, height)", 4483},
    {"satellite.window.number_box(least, most)", 4492},
    {"satellite.window.one_of(items)", 4512},
    {"satellite.window.picture(path)", 4502},
    {"satellite.window.progress", 4493},
    {"satellite.window.progress()", 4494},
    {"satellite.window.row", 4496},
    {"satellite.window.row()", 4497},
    {"satellite.window.scroll", 4503},
    {"satellite.window.scroll()", 4504},
    {"satellite.window.slider(least, most)", 4491},
    {"satellite.window.split", 4506},
    {"satellite.window.split()", 4507},
    {"satellite.window.switch", 4489},
    {"satellite.window.switch()", 4490},
    {"satellite.window.tabs", 4510},
    {"satellite.window.tabs()", 4511},
    {"satellite.window.text_area(text)", 4487},
    {"satellite.window.text_box(text)", 4486},
};

inline constexpr std::size_t kSpelledWordCount = sizeof kSpelledWords / sizeof kSpelledWords[0];

// THE CONVERSION. A .sat file stores a word as int int int int; this is how
// that becomes the one 16-bit code the interpreter holds.
//
//     code_of(1, 5, 1)  ->  4163   satellite.console.display
//     code_of(1)        ->  4097   satellite
//
// ANSWERS 0 -- the registry's "nothing" -- when the word has no code: not in
// the table, deeper than kMaxDepth, or a number past 255. The caller then
// writes word_number_token and the numbers, which has no ceiling, so a
// language with no limits keeps none here either.
inline token::Code code_of(const int *numbers, std::size_t depth)
{
    const std::uint64_t key = key_of(numbers, depth);
    if (key == 0) return 0;
    std::size_t low = 0, high = kKeyedWordCount;
    while (low < high) {
        const std::size_t middle = low + (high - low) / 2;
        if (kKeyedWords[middle].key < key) low = middle + 1;
        else high = middle;
    }
    if (low < kKeyedWordCount && kKeyedWords[low].key == key) return kKeyedWords[low].code;
    return 0;
}

// code_of(1, 5, 1) -- the spelling a .sat file's int int int int reads as.
//
// CONSTRAINED TO INTEGERS on purpose: unconstrained, this swallowed
// code_of(pointer, depth) too and tried to cast the pointer to an int.
template <class... Numbers>
    requires (sizeof...(Numbers) > 0 && (... && std::is_integral_v<Numbers>))
inline token::Code code_of(Numbers... numbers)
{
    const int written[] = {static_cast<int>(numbers)...};
    return code_of(written, sizeof...(Numbers));
}

// The way back, for whatever writes a .sat file out again. Answers nullptr
// and leaves `depth` at 0 when `code` is not a word this table holds.
inline const int *numbers_of(token::Code code, unsigned int &depth)
{
    depth = 0;
    if (code < kFirst || code >= kFirst + kWordFactsCount) return nullptr;
    const WordFacts &facts = kWordFacts[code - kFirst];
    depth = facts.depth;
    return facts.numbers;
}

// The code for a spelling, or 0. The lexer's way in: it has the TEXT
// satellite.console.display and wants 4163, without ever building numbers.
inline token::Code code_of_spelling(std::string_view path)
{
    std::size_t low = 0, high = kSpelledWordCount;
    while (low < high) {
        const std::size_t middle = low + (high - low) / 2;
        if (std::string_view(kSpelledWords[middle].path) < path) low = middle + 1;
        else high = middle;
    }
    if (low < kSpelledWordCount && std::string_view(kSpelledWords[low].path) == path)
        return kSpelledWords[low].code;
    return 0;
}

// "satellite.console.display", or nullptr. What the converters print.
inline const char *spelling_of(token::Code code)
{
    if (code < kFirst || code >= kFirst + kWordFactsCount) return nullptr;
    return kWordFacts[code - kFirst].path;
}

} // namespace word
} // namespace satellite004
