#!/usr/bin/env python3
# satellite/licenses/make_license_data.py -- every licence, compiled INTO satl.
#
#     python3 satellite/licenses/make_license_data.py [output.cpp]
#
# WHY THE TEXT IS IN THE BINARY AND NOT BESIDE IT. satl's whole point is one file
# that needs nothing installed. A licence notice that lives in a folder beside the
# binary is a notice that is gone the moment somebody copies the binary somewhere --
# and several of these licences require the notice to travel WITH the distributed
# product, not near it. gtk/roaring's BSD-3-Clause clause 2 says "binary" in so many
# words; libpng's clause 3 forbids removing the notice; pcre2's condition 2 wants
# every copyright line reproduced. Embedding is the only way those stay true after
# `cp build/satl ~/.local/bin/`.
#
# It costs 284 KB inside an 89 MB binary: 0.3%, against a 12 GB ceiling.
#
# NOT A GResource, unlike window_data.py's fonts and keyboard data. That one can
# assume glib, because it only exists when GTK is compiled in. This must work in
# `make` as well as `make GTK=vendor`, so it is plain C++ with no dependency at all.
#
# THE SOURCE OF TRUTH IS licenses/<project>/license.txt, the same files the website
# and THIRD-PARTY-NOTICES.txt are built from. Three shapes, one source, generated --
# they cannot drift.
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
LICENSES = os.path.join(ROOT, "licenses")

# A raw-string delimiter that cannot appear in a licence. Checked below rather than
# hoped for: a delimiter collision would not fail to compile, it would end the string
# early and silently truncate somebody's licence.
DELIMITER = "SATL_LICENCE"
CLOSING = ")" + DELIMITER + '"'


def rows():
    if not os.path.isdir(LICENSES):
        sys.exit("make_license_data.py: no " + LICENSES)
    names = sorted(n for n in os.listdir(LICENSES)
                   if os.path.isfile(os.path.join(LICENSES, n, "license.txt")))
    if not names:
        sys.exit("make_license_data.py: no licenses/<project>/license.txt found")
    # satellite first -- it is the licence FOR the language, and the rest are what the
    # language carries. The same order THIRD-PARTY-NOTICES.txt uses, so a number means
    # the same thing in both.
    if "satellite" in names:
        names.remove("satellite")
        names.insert(0, "satellite")
    out = []
    for name in names:
        with open(os.path.join(LICENSES, name, "license.txt"), encoding="utf-8") as handle:
            text = handle.read()
        if CLOSING in text:
            sys.exit("make_license_data.py: " + name + " contains the raw-string "
                     "delimiter " + CLOSING + " and would be truncated silently. "
                     "Change DELIMITER.")
        out.append((name, text))
    return out


def main():
    target = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "build", "generated", "license_data.cpp")
    os.makedirs(os.path.dirname(target), exist_ok=True)
    data = rows()

    lines = [
        "// GENERATED by satellite/licenses/make_license_data.py from licenses/<project>/",
        "// license.txt. DO NOT EDIT -- edit nothing, and rebuild.",
        "//",
        "// Every text is byte-for-byte what upstream shipped. A licence that has been",
        "// reformatted is no longer the licence, and several of these require the notice",
        "// be reproduced exactly.",
        "",
        '#include "../../satellite/licenses/licenses.hpp"',
        "",
        "namespace satellite004 {",
        "",
        "const std::vector<licence_row> &licence_rows()",
        "{",
        "    static const std::vector<licence_row> rows = {",
    ]
    for name, text in data:
        lines.append('        {"' + name + '", R"' + DELIMITER + "(" + text + ")" + DELIMITER + '"},')
    lines += [
        "    };",
        "    return rows;",
        "}",
        "",
        "} // namespace satellite004",
        "",
    ]

    with open(target, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))

    total = sum(len(t) for _, t in data)
    print("license_data.cpp: %d licences, %.0f KB of text" % (len(data), total / 1024.0))


if __name__ == "__main__":
    main()
