#!/bin/sh
# licenses/make_notices.sh -- build THIRD-PARTY-NOTICES.txt from the folders.
#
#     sh licenses/make_notices.sh
#
# ONE FILE HOLDING EVERY LICENCE, for anywhere that wants a single document rather
# than twenty-six: a website tab, a distributed package, a print-out. It is GENERATED
# rather than maintained so it cannot drift from the folders, which are the source of
# truth -- add a folder and re-run this, never edit the output.
#
# The per-folder files stay exactly as they are. Some places want one document and some
# want one file per project, and both are the same content.
set -eu

here=$(cd "$(dirname "$0")" && pwd)
cd "$here"
out=THIRD-PARTY-NOTICES.txt
names=$(ls -1 */license.txt 2>/dev/null | sed 's|/license.txt||' | sort)
[ -n "$names" ] || { echo "licenses: no */license.txt found" >&2; exit 1; }

# satellite first: it is the licence for the language, and the rest are what the
# language carries. Everything else stays alphabetical.
ordered="satellite $(echo "$names" | grep -v '^satellite$' | tr '\n' ' ')"

{
    echo "SATELLITE -- LICENCES"
    echo "====================="
    echo
    echo "satellite is MIT. The satl interpreter STATICALLY LINKS the projects below,"
    echo "which means it distributes them, so each one's licence is reproduced here in"
    echo "full and unaltered."
    echo
    echo "\"The GTK licence\" is not one licence. GTK is many separate upstream projects"
    echo "with many sets of copyright holders, and they do not agree with each other:"
    echo "GTK and pango are under the GNU Library GPL, glib and gdk-pixbuf under the"
    echo "LGPL, FreeType under the FreeType Licence, and zlib, libpng, pcre2, libtiff,"
    echo "libjpeg-turbo and fontconfig each wrote their own."
    echo
    echo "Generated by licenses/make_notices.sh from licenses/<project>/license.txt."
    echo "Do not edit this file; edit nothing, and re-run the script."
    echo
    echo "CONTENTS"
    echo "--------"
    n=0
    for name in $ordered; do
        n=$((n + 1))
        printf '  %2d. %s\n' "$n" "$name"
    done
    echo

    n=0
    for name in $ordered; do
        n=$((n + 1))
        echo
        echo "================================================================================"
        printf '  %d. %s\n' "$n" "$name"
        echo "================================================================================"
        echo
        cat "$name/license.txt"
        echo
    done
} > "$out"

echo "licenses: wrote $out -- $(grep -c '' "$out") lines, $(du -h "$out" | cut -f1), $(echo "$ordered" | wc -w) projects"
