// satellite/satellite_variable_window/window_spill.cpp -- writing the carried data
// out. The header says why each piece is fatal without it.
//
// COMPILED ONLY WHERE pkg-config FINDS gtk4, like the rest of this folder.

#include "window_spill.hpp"

#include <gio/gio.h>
#include <glib.h>
#include <glib/gstdio.h>

#include <cerrno>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

// GENERATED by make_window_data.py from vendor/xkb/, vendor/fonts/ and GTK's
// compiled schemas. Registering by hand rather than through a constructor
// attribute, so the moment it happens is written down here and not implied.
extern "C" GResource *satl_window_data_get_resource(void);

namespace satellite004 {
namespace {

const char *const kPrefix = "/org/satellite/window";

// HOW BIG THE CARRIED DATA IS, which names the spill directory. Two satls built
// from different data then cannot share one spill, and the check costs a walk of
// the resource index rather than of the disk.
unsigned long long int carried_bytes(const std::string &at, unsigned long long int &files)
{
    unsigned long long int total = 0;
    char **names = g_resources_enumerate_children(at.c_str(), G_RESOURCE_LOOKUP_FLAGS_NONE, nullptr);
    if (names == nullptr)
        return 0;
    for (char **name = names; *name != nullptr; ++name) {
        const std::string child = at + "/" + *name;
        if (child.back() == '/' || g_str_has_suffix(*name, "/")) {
            total += carried_bytes(child.substr(0, child.size() - 1), files);
            continue;
        }
        gsize size = 0;
        guint32 flags = 0;
        if (g_resources_get_info(child.c_str(), G_RESOURCE_LOOKUP_FLAGS_NONE, &size, &flags, nullptr)) {
            total += size;
            ++files;
        } else {
            total += carried_bytes(child, files);      // it was a directory after all
        }
    }
    g_strfreev(names);
    return total;
}

bool write_one(const std::string &resource, const std::string &path, std::string &why)
{
    GBytes *bytes = g_resources_lookup_data(resource.c_str(), G_RESOURCE_LOOKUP_FLAGS_NONE, nullptr);
    if (bytes == nullptr) {
        why = "carried file " + resource + " is not in the binary";
        return false;
    }
    gsize size = 0;
    gconstpointer data = g_bytes_get_data(bytes, &size);
    GError *trouble = nullptr;
    const gboolean ok = g_file_set_contents(path.c_str(), static_cast<const char *>(data),
                                            static_cast<gssize>(size), &trouble);
    g_bytes_unref(bytes);
    if (ok == FALSE) {
        why = std::string("could not write ") + path + " -- " +
              (trouble != nullptr ? trouble->message : "unknown");
        if (trouble != nullptr) g_error_free(trouble);
        return false;
    }
    return true;
}

// EVERY FILE UNDER `at`, DIRECTORIES AND ALL. g_resources_enumerate_children does
// not say which children are directories, so a child that has no info IS one --
// which is also how carried_bytes counts.
bool write_tree(const std::string &at, const std::string &into, std::string &why)
{
    if (g_mkdir_with_parents(into.c_str(), 0700) != 0) {
        why = "could not make " + into + " -- " + std::strerror(errno);
        return false;
    }
    char **names = g_resources_enumerate_children(at.c_str(), G_RESOURCE_LOOKUP_FLAGS_NONE, nullptr);
    if (names == nullptr)
        return true;
    bool went = true;
    for (char **name = names; went && *name != nullptr; ++name) {
        std::string leaf(*name);
        const bool a_folder = !leaf.empty() && leaf.back() == '/';
        if (a_folder) leaf.pop_back();
        const std::string child = at + "/" + leaf;
        if (a_folder) {
            went = write_tree(child, into + "/" + leaf, why);
            continue;
        }
        gsize size = 0;
        guint32 flags = 0;
        if (g_resources_get_info(child.c_str(), G_RESOURCE_LOOKUP_FLAGS_NONE, &size, &flags, nullptr))
            went = write_one(child, into + "/" + leaf, why);
        else
            went = write_tree(child, into + "/" + leaf, why);
    }
    g_strfreev(names);
    return went;
}

} // namespace

bool spill_what_gtk_needs(std::string &why)
{
    g_resources_register(satl_window_data_get_resource());

    unsigned long long int files = 0;
    const unsigned long long int bytes = carried_bytes(kPrefix, files);
    if (files == 0) {
        why = "this satl carries no window data -- make_window_data.py did not run";
        return false;
    }

    // $XDG_RUNTIME_DIR IS THE RIGHT HOME: it is per-user, already private (0700),
    // on tmpfs, and the system clears it at logout -- so satl never accumulates
    // spills and never has to decide when to delete one. With none set, a temp
    // directory, which is the same bargain a machine without a session offers.
    const char *runtime = g_getenv("XDG_RUNTIME_DIR");
    std::string home;
    if (runtime != nullptr && *runtime != '\0') {
        home = std::string(runtime) + "/satl-window-" + std::to_string(bytes);
    } else {
        GError *trouble = nullptr;
        char *made = g_dir_make_tmp("satl-window-XXXXXX", &trouble);
        if (made == nullptr) {
            why = std::string("no XDG_RUNTIME_DIR and no temp directory -- ") +
                  (trouble != nullptr ? trouble->message : "unknown");
            if (trouble != nullptr) g_error_free(trouble);
            return false;
        }
        home = made;
        g_free(made);
    }

    // THE MARKER IS WRITTEN LAST AND IS THE ONLY THING TRUSTED. A spill that was
    // interrupted -- a full disk, a Ctrl-C, a machine that went down -- leaves a
    // directory that LOOKS right, and a partial xkb tree is a SIGSEGV rather than
    // a warning. So completeness is a fact recorded after the fact, never inferred
    // from the directory being there.
    const std::string marker = home + "/.complete";
    const std::string expect = std::to_string(files) + " " + std::to_string(bytes);
    char *found = nullptr;
    const bool already = g_file_get_contents(marker.c_str(), &found, nullptr, nullptr) == TRUE &&
                         found != nullptr && expect == found;
    g_free(found);

    if (!already) {
        if (g_mkdir_with_parents(home.c_str(), 0700) != 0) {
            why = "could not make " + home + " -- " + std::strerror(errno);
            return false;
        }
        g_remove(marker.c_str());                     // never a stale marker over a new spill
        if (!write_tree(kPrefix, home, why))
            return false;

        // fonts.conf CANNOT BE CARRIED FINISHED: it has to name the directory it
        // was spilled into, which nothing knows until now.
        char *pattern = nullptr;
        if (!g_file_get_contents((home + "/fonts.conf.in").c_str(), &pattern, nullptr, nullptr)) {
            why = "the carried fonts.conf did not spill";
            return false;
        }
        std::string filled(pattern);
        g_free(pattern);
        for (const auto &swap : {std::pair<std::string, std::string>{"@SATL_FONT_DIR@", home + "/fonts"},
                                 std::pair<std::string, std::string>{"@SATL_CACHE_DIR@", home + "/fontcache"}}) {
            for (std::size_t at = filled.find(swap.first); at != std::string::npos;
                 at = filled.find(swap.first, at))
                filled.replace(at, swap.first.size(), swap.second);
        }
        if (!g_file_set_contents((home + "/fonts.conf").c_str(), filled.c_str(),
                                 static_cast<gssize>(filled.size()), nullptr)) {
            why = "could not write " + home + "/fonts.conf";
            return false;
        }
        g_mkdir_with_parents((home + "/fontcache").c_str(), 0700);
        if (!g_file_set_contents(marker.c_str(), expect.c_str(),
                                 static_cast<gssize>(expect.size()), nullptr)) {
            why = "could not mark " + home + " complete";
            return false;
        }
    }

    // g_setenv AND NOT setenv: glib keeps its own view of the environment on some
    // platforms, and these are read by glib and by libraries glib started.
    // OVERWRITE IS TRUE for all three. A machine that HAS xkb data still gets
    // ours, because ours is the version this GTK was built against -- and the
    // build deliberately compiled in a nonexistent default so a miss is loud.
    g_setenv("XKB_CONFIG_ROOT", (home + "/xkb").c_str(), TRUE);
    g_setenv("FONTCONFIG_FILE", (home + "/fonts.conf").c_str(), TRUE);
    g_setenv("FONTCONFIG_PATH", home.c_str(), TRUE);
    // GSETTINGS_SCHEMA_DIR *PREPENDS*, so this cannot regress a machine that has
    // its own schemas -- ours are found first and theirs still work.
    g_setenv("GSETTINGS_SCHEMA_DIR", (home + "/schemas").c_str(), TRUE);
    return true;
}

} // namespace satellite004
