#!/usr/bin/env python3
"""What `satellite.help()` prints -- taken from the interpreter, not rebuilt.

THIS FILE USED TO RECONSTRUCT THE LISTING AND THAT WAS THE DRIFT IT DESCRIBED.
Before M18 there was no `satellite.help` to ask, so this script walked
`nodes.tsv` and a hand-written FRONT_END set and assembled what help WOULD print
-- which is a second implementation of the milestone's whole subject, free to
disagree with the first the moment either moved. It disagreed the day help was
built: the real walk names 14 topics and this named 13, because help now names
itself.

SO IT RUNS THE PROGRAM. `satellite.help()` is three lines of satellite; the
answer is whatever the interpreter in this tree says it is, and HELP.md carries
that verbatim. The front-end set it used to hold now lives in `words.def`'s
fourth list as data, which is where PLAN M18 says it has to be.
"""
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SATL = os.path.join(ROOT, "satl")
DEF = os.path.join(ROOT, "src", "satellite_help", "help.def")

PROGRAM = """satellite.include(satellite)

satellite.capsule satellite.main()
{
    satellite.help()
}
"""


def render():
    if not os.path.exists(SATL):
        sys.exit("topics.py: no ./satl -- run `make` first; the listing is what "
                 "the interpreter prints and there is nothing else to ask")

    # AND THE BINARY HAS TO BE NEWER THAN THE TABLE IT PRINTS. help.def is
    # generated by the same run of gen.py that calls this, so a satl built
    # before the entries were last edited would answer with the old text and
    # HELP.md would record it as current -- a stale document that looks
    # measured, which is worse than one that looks written.
    if os.path.exists(DEF) and os.path.getmtime(SATL) < os.path.getmtime(DEF):
        sys.exit("topics.py: ./satl is older than src/satellite_help/help.def "
                 "-- run `make`, then run this again")

    with tempfile.TemporaryDirectory() as where:
        path = os.path.join(where, "topics.satl")
        with open(path, "w") as f:
            f.write(PROGRAM)
        env = dict(os.environ, SATL_NO_WINDOW="1")
        done = subprocess.run([SATL, path], capture_output=True, text=True,
                              stdin=subprocess.DEVNULL, env=env, cwd=where)
    if done.returncode != 0:
        sys.exit("topics.py: satl refused `satellite.help()`:\n" + done.stderr)
    return done.stdout.rstrip("\n")


if __name__ == "__main__":
    print(render())
